//HintName: ShipSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class ShipSagaCorrelationDispatch
{
    private static readonly ShipSaga _probe = new ShipSaga();

    public static global::Sample.ShipId GetKey(global::Sample.ShipQueued e) => _probe.Correlation(e);
}
