//HintName: TwoStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class TwoStepSagaBuilderExtensions
{
    public static ISagaBuilder AddTwoStepSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<TwoStepSaga, global::Sample.OrderId>, InMemorySagaStore<TwoStepSaga, global::Sample.OrderId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<TwoStepSaga, global::Sample.OrderId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<TwoStepSaga>, TwoStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<TwoStepSaga, global::Sample.OrderId>, SagaManager<TwoStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, TwoStepSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, TwoStepSaga_StockReserved_Handler>();
        return builder;
    }
}

internal sealed class TwoStepSagaCompensationDispatcher : ISagaCompensationDispatcher<TwoStepSaga>
{
    private readonly IMediator _mediator;
    public TwoStepSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(TwoStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(TwoStepSagaFsm.Trigger.CompensateDone);
    }
}
