//HintName: ShipSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class ShipSagaBuilderExtensions
{
    public static ISagaBuilder AddShipSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<ShipSaga, global::Sample.ShipId>, InMemorySagaStore<ShipSaga, global::Sample.ShipId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<ShipSaga, global::Sample.ShipId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.ShipId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<ShipSaga>, ShipSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<ShipSaga, global::Sample.ShipId>, SagaManager<ShipSaga, global::Sample.ShipId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.ShipQueued>, ShipSaga_ShipQueued_Handler>();
        return builder;
    }
}

internal sealed class ShipSagaCompensationDispatcher : ISagaCompensationDispatcher<ShipSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public ShipSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(ShipSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(ShipSagaFsm.Trigger.CompensateDone);
    }
}
