//HintName: OrderSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class OrderSagaCorrelationDispatch
{
    private static readonly OrderSaga _probe = new OrderSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
}
