//HintName: TwoStepSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class TwoStepSagaCorrelationDispatch
{
    private static readonly TwoStepSaga _probe = new TwoStepSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.StockReserved e) => _probe.Correlation(e);
}
