//HintName: TwoStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class TwoStepSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="TwoStepSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithTwoStepSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<TwoStepSaga, global::Sample.OrderId>, InMemorySagaStore<TwoStepSaga, global::Sample.OrderId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<TwoStepSaga, global::Sample.OrderId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<TwoStepSaga>, TwoStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<TwoStepSaga, global::Sample.OrderId>, SagaManager<TwoStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, TwoStepSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, TwoStepSaga_StockReserved_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithTwoStepSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithTwoStepSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddTwoStepSaga(this ISagaBuilder builder)
        => builder.WithTwoStepSaga();
}

internal sealed class TwoStepSagaCompensationDispatcher : ISagaCompensationDispatcher<TwoStepSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public TwoStepSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(TwoStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(TwoStepSagaFsm.Trigger.CompensateDone);
    }
}
