//HintName: OrderSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class OrderSagaBuilderExtensions
{
    public static ISagaBuilder AddOrderSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<OrderSaga, global::Sample.OrderId>, InMemorySagaStore<OrderSaga, global::Sample.OrderId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<OrderSaga, global::Sample.OrderId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<OrderSaga>, OrderSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<OrderSaga, global::Sample.OrderId>, SagaManager<OrderSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, OrderSaga_OrderPlaced_Handler>();
        return builder;
    }
}

internal sealed class OrderSagaCompensationDispatcher : ISagaCompensationDispatcher<OrderSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public OrderSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(OrderSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(OrderSagaFsm.Trigger.CompensateDone);
    }
}
