//HintName: OrderSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class OrderSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="OrderSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithOrderSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<OrderSaga, global::Sample.OrderId>, InMemorySagaStore<OrderSaga, global::Sample.OrderId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<OrderSaga, global::Sample.OrderId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<OrderSaga>, OrderSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<OrderSaga, global::Sample.OrderId>, SagaManager<OrderSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, OrderSaga_OrderPlaced_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithOrderSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithOrderSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddOrderSaga(this ISagaBuilder builder)
        => builder.WithOrderSaga();
}

internal sealed class OrderSagaCompensationDispatcher : ISagaCompensationDispatcher<OrderSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public OrderSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(OrderSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(OrderSagaFsm.Trigger.CompensateDone);
    }
}
