//HintName: SingleStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class SingleStepSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="SingleStepSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithSingleStepSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<SingleStepSaga, global::Sample.OrderId>, InMemorySagaStore<SingleStepSaga, global::Sample.OrderId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<SingleStepSaga, global::Sample.OrderId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<SingleStepSaga>, SingleStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<SingleStepSaga, global::Sample.OrderId>, SagaManager<SingleStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, SingleStepSaga_OrderPlaced_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithSingleStepSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithSingleStepSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddSingleStepSaga(this ISagaBuilder builder)
        => builder.WithSingleStepSaga();
}

internal sealed class SingleStepSagaCompensationDispatcher : ISagaCompensationDispatcher<SingleStepSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public SingleStepSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(SingleStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(SingleStepSagaFsm.Trigger.CompensateDone);
    }
}
