//HintName: SagaCommandRegistry.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using ZeroAlloc.Mediator;
using ZeroAlloc.Serialisation;

namespace ZeroAlloc.Saga.Generated;

/// <summary>
/// Per-compilation table that maps an outbox entry's <c>typeName</c> to a typed
/// deserialize-via-<see cref="ISerializer{T}"/> and dispatch-via-<see cref="IMediator.Send"/> path.
/// <see cref="GeneratedSagaCommandSource"/> calls it for every saga command that
/// <c>ZeroAlloc.Saga.Outbox</c>'s outbox dispatchers read from the outbox.
/// </summary>
internal static class SagaCommandRegistry
{
    // Type.FullName of every saga step and compensation command. OutboxSagaCommandDispatcher
    // writes the same expression as the outbox entry's type name, so nested and generic
    // command types match as well.
    private static readonly string[] s_typeNames =
    {
        typeof(global::Sample.ReserveCmd).FullName!,
    };

    internal static async ValueTask DispatchAsync(
        string typeName,
        ReadOnlyMemory<byte> bytes,
        IServiceProvider services,
        IMediator mediator,
        CancellationToken ct)
    {
        if (string.Equals(typeName, s_typeNames[0], StringComparison.Ordinal))
        {
            var serializer = services.GetRequiredService<ISerializer<global::Sample.ReserveCmd>>();
            var cmd = serializer.Deserialize(bytes.Span);
            if (cmd is null)
                throw new InvalidOperationException("ISerializer.Deserialize returned null for Sample.ReserveCmd.");
            await mediator.Send(cmd, ct).ConfigureAwait(false);
            return;
        }

        throw new InvalidOperationException(
            $"Unknown saga command type '{typeName}'. The outbox entry references a type that the Saga generator did not emit a dispatcher for.");
    }
}
