//HintName: Sample_ReserveCmd.SagaSerializable.g.cs
// <auto-generated/>
#nullable enable
using ZeroAlloc.Serialisation;

namespace Sample;

[ZeroAllocSerializable(SerializationFormat.SystemTextJson)]
partial record struct ReserveCmd;
