//HintName: SingleStepSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class SingleStepSagaCorrelationDispatch
{
    private static readonly SingleStepSaga _probe = new SingleStepSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
}
