//HintName: SagaCommandRegistry.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using ZeroAlloc.Mediator;
using ZeroAlloc.Serialisation;

namespace ZeroAlloc.Saga.Generated;

/// <summary>
/// Per-compilation switch table that maps an outbox entry's <c>typeName</c> to a typed
/// deserialize-via-<see cref="ISerializer{T}"/> and dispatch-via-<see cref="IMediator.Send"/> path.
/// Consumed by <c>ZeroAlloc.Saga.Outbox.OutboxSagaCommandPoller</c>.
/// </summary>
public static class SagaCommandRegistry
{
    public static async ValueTask DispatchAsync(
        string typeName,
        ReadOnlyMemory<byte> bytes,
        IServiceProvider services,
        IMediator mediator,
        CancellationToken ct)
    {
        switch (typeName)
        {
            case "Sample.ReserveCmd":
            {
                var serializer = services.GetRequiredService<ISerializer<global::Sample.ReserveCmd>>();
                var cmd = serializer.Deserialize(bytes.Span);
                if (cmd is null)
                    throw new InvalidOperationException("ISerializer.Deserialize returned null for Sample.ReserveCmd.");
                await mediator.Send(cmd, ct).ConfigureAwait(false);
                return;
            }
            default:
                throw new InvalidOperationException(
                    $"Unknown saga command type '{typeName}'. The outbox entry references a type that the Saga generator did not emit a dispatcher for.");
        }
    }
}
