//HintName: AuditSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class AuditSagaBuilderExtensions
{
    public static ISagaBuilder AddAuditSaga(this ISagaBuilder builder)
    {
        builder.Services.TryAddSingleton<ISagaStore<AuditSaga, global::Sample.OrderId>, InMemorySagaStore<AuditSaga, global::Sample.OrderId>>();
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<AuditSaga>, AuditSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<AuditSaga, global::Sample.OrderId>, SagaManager<AuditSaga, global::Sample.OrderId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderShipped>, AuditSaga_OrderShipped_Handler>();
        return builder;
    }
}

internal sealed class AuditSagaCompensationDispatcher : ISagaCompensationDispatcher<AuditSaga>
{
    private readonly IMediator _mediator;
    public AuditSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(AuditSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(AuditSagaFsm.Trigger.CompensateDone);
    }
}
