//HintName: StateFieldSaga_OrderPlaced_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class StateFieldSaga_OrderPlaced_Handler : INotificationHandler<global::Sample.OrderPlaced>
{
    private readonly ISagaStore<StateFieldSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly ISagaCommandDispatcher _dispatcher;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<StateFieldSaga_OrderPlaced_Handler> _log;

    public StateFieldSaga_OrderPlaced_Handler(ISagaStore<StateFieldSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, ISagaCommandDispatcher dispatcher, SagaRetryOptions retry, ILogger<StateFieldSaga_OrderPlaced_Handler> log)
    {
        _store = store;
        _locks = locks;
        _dispatcher = dispatcher;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.OrderPlaced @event, CancellationToken ct)
    {
        var key = StateFieldSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            try
            {
                var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
                if (!saga.Fsm.TryFire(StateFieldSagaFsm.Trigger.OrderPlaced))
                {
                    _log.LogDebug("Saga {Saga}: late OrderPlaced for key {Key}; ignored", "StateFieldSaga", key);
                    return;
                }

                var cmd = saga.Reserve(@event);
                await _dispatcher.DispatchAsync(cmd, ct).ConfigureAwait(false);

                saga.Fsm.TryFire(StateFieldSagaFsm.Trigger.Complete);
                await _store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}", "StateFieldSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsEfCoreConflict(ex))
            {
                throw new SagaConcurrencyException("StateFieldSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsEfCoreConflict(Exception ex)
    {
        var typeName = ex.GetType().FullName;
        return typeName == "Microsoft.EntityFrameworkCore.DbUpdateException"
            || typeName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException";
    }
}
