//HintName: FulfillmentSaga_OrderPlaced_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class FulfillmentSaga_OrderPlaced_Handler : INotificationHandler<global::Sample.OrderPlaced>
{
    private readonly ISagaStore<FulfillmentSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly IMediator _mediator;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<FulfillmentSaga_OrderPlaced_Handler> _log;

    public FulfillmentSaga_OrderPlaced_Handler(ISagaStore<FulfillmentSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, IMediator mediator, SagaRetryOptions retry, ILogger<FulfillmentSaga_OrderPlaced_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.OrderPlaced @event, CancellationToken ct)
    {
        var key = FulfillmentSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            try
            {
                var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
                if (!saga.Fsm.TryFire(FulfillmentSagaFsm.Trigger.OrderPlaced))
                {
                    _log.LogDebug("Saga {Saga}: late OrderPlaced for key {Key}; ignored", "FulfillmentSaga", key);
                    return;
                }

                var cmd = saga.Reserve(@event);
                await _mediator.Send(cmd, ct).ConfigureAwait(false);

                saga.Fsm.TryFire(FulfillmentSagaFsm.Trigger.Complete);
                await _store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (ex.GetType().FullName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException" && attempts < _retry.MaxRetryAttempts)
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}", "FulfillmentSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (ex.GetType().FullName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException")
            {
                throw new SagaConcurrencyException("FulfillmentSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }
}
