//HintName: StateFieldSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class StateFieldSagaCorrelationDispatch
{
    private static readonly StateFieldSaga _probe = new StateFieldSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
}
