//HintName: App.OrderSaga.Handler.App.CompensateDone.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace App;

internal sealed class OrderSaga_App_CompensateDone_Handler : INotificationHandler<global::App.CompensateDone>
{
    // Scope-per-attempt: see the same-named comment in the forward handler.
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly SagaLockManager<int> _locks;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<OrderSaga_App_CompensateDone_Handler> _log;

    public OrderSaga_App_CompensateDone_Handler(IServiceScopeFactory scopeFactory, SagaLockManager<int> locks, SagaRetryOptions retry, ILogger<OrderSaga_App_CompensateDone_Handler> log)
    {
        _scopeFactory = scopeFactory;
        _locks = locks;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::App.CompensateDone @event, CancellationToken ct)
    {
        // Resolve the correlation key for this failure event.
        var key = OrderSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            using var scope = _scopeFactory.CreateScope();
            var store = scope.ServiceProvider.GetRequiredService<ISagaStore<OrderSaga, int>>();
            var dispatcher = scope.ServiceProvider.GetRequiredService<ISagaCommandDispatcher>();
            try
            {
                var saga = await store.TryLoadAsync(key, ct).ConfigureAwait(false);
                if (saga is null)
                {
                    _log.LogWarning("Saga {Saga}: orphan App.CompensateDone for key {Key}; no instance to compensate", "OrderSaga", key);
                    return;
                }

                var stateAtFailure = saga.Fsm.Current;
                if (!saga.Fsm.TryFire(OrderSagaFsm.Trigger.App_CompensateDone))
                {
                    _log.LogDebug("Saga {Saga}: App.CompensateDone not valid in state {State} for key {Key}; ignored", "OrderSaga", stateAtFailure, key);
                    return;
                }

                // Reverse-cascade compensation: walk back from stateAtFailure to Step1.
                // Re-dispatch contract: if RemoveAsync below throws an EF Core conflict
                // (third party deleted/updated row mid-compensation), the surrounding
                // retry loop re-enters this try block. On retry, TryLoadAsync may return
                // null (just-deleted) and the handler returns silently; otherwise the
                // compensation commands below may be dispatched a second time. The
                // "idempotency is the user's responsibility" contract (ZASAGA015) covers this.
                switch (stateAtFailure)
                {
                    case OrderSagaFsm.State.Step1:
                        await dispatcher.DispatchAsync(saga.Undo(), ct).ConfigureAwait(false);
                        break;
                    default: break;
                }

                saga.Fsm.TryFire(OrderSagaFsm.Trigger.CompensateDone);
                await store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsBackendConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on compensation for key {Key}, retry {Attempt}/{Max}", "OrderSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsBackendConflict(ex))
            {
                throw new SagaConcurrencyException("OrderSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsBackendConflict(Exception ex)
    {
        // Any store signals a retryable conflict by implementing
        // ISagaConcurrencyConflict, so no backend type names appear here.
        return ex is global::ZeroAlloc.Saga.ISagaConcurrencyConflict;
    }
}
