//HintName: TypedIdFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class TypedIdFieldSagaBuilderExtensions
{
    public static ISagaBuilder AddTypedIdFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<TypedIdFieldSaga, global::Sample.CustomerId>, InMemorySagaStore<TypedIdFieldSaga, global::Sample.CustomerId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<TypedIdFieldSaga, global::Sample.CustomerId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.CustomerId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<TypedIdFieldSaga>, TypedIdFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<TypedIdFieldSaga, global::Sample.CustomerId>, SagaManager<TypedIdFieldSaga, global::Sample.CustomerId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Activated>, TypedIdFieldSaga_Activated_Handler>();
        return builder;
    }
}

internal sealed class TypedIdFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<TypedIdFieldSaga>
{
    private readonly IMediator _mediator;
    public TypedIdFieldSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(TypedIdFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(TypedIdFieldSagaFsm.Trigger.CompensateDone);
    }
}
