//HintName: TypedIdFieldSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class TypedIdFieldSagaCorrelationDispatch
{
    private static readonly TypedIdFieldSaga _probe = new TypedIdFieldSaga();

    public static global::Sample.CustomerId GetKey(global::Sample.Activated e) => _probe.Correlation(e);
}
