//HintName: FulfillmentSaga_OrderPlaced_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class FulfillmentSaga_OrderPlaced_Handler : INotificationHandler<global::Sample.OrderPlaced>
{
    private readonly ISagaStore<FulfillmentSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<FulfillmentSaga_OrderPlaced_Handler> _log;

    public FulfillmentSaga_OrderPlaced_Handler(ISagaStore<FulfillmentSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, IMediator mediator, ILogger<FulfillmentSaga_OrderPlaced_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.OrderPlaced @event, CancellationToken ct)
    {
        var key = FulfillmentSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
        if (!saga.Fsm.TryFire(FulfillmentSagaFsm.Trigger.OrderPlaced))
        {
            _log.LogDebug("Saga {Saga}: late OrderPlaced for key {Key}; ignored", "FulfillmentSaga", key);
            return;
        }

        var cmd = saga.Reserve(@event);
        await _mediator.Send(cmd, ct).ConfigureAwait(false);

        saga.Fsm.TryFire(FulfillmentSagaFsm.Trigger.Complete);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
