//HintName: ThreeStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class ThreeStepSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="ThreeStepSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithThreeStepSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<ThreeStepSaga, global::Sample.OrderId>, InMemorySagaStore<ThreeStepSaga, global::Sample.OrderId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<ThreeStepSaga, global::Sample.OrderId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<ThreeStepSaga>, ThreeStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<ThreeStepSaga, global::Sample.OrderId>, SagaManager<ThreeStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, ThreeStepSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, ThreeStepSaga_StockReserved_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentCharged>, ThreeStepSaga_PaymentCharged_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentDeclined>, ThreeStepSaga_PaymentDeclined_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithThreeStepSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithThreeStepSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddThreeStepSaga(this ISagaBuilder builder)
        => builder.WithThreeStepSaga();
}

internal sealed class ThreeStepSagaCompensationDispatcher : ISagaCompensationDispatcher<ThreeStepSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public ThreeStepSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(ThreeStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            case ThreeStepSagaFsm.State.Step3:
                await _dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                await _dispatcher.DispatchAsync(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            case ThreeStepSagaFsm.State.Step2:
                await _dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                await _dispatcher.DispatchAsync(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            case ThreeStepSagaFsm.State.Step1:
                await _dispatcher.DispatchAsync(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            default: break;
        }
        saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.CompensateDone);
    }
}
