//HintName: PrimitiveFieldsSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class PrimitiveFieldsSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="PrimitiveFieldsSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithPrimitiveFieldsSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<PrimitiveFieldsSaga, int>, InMemorySagaStore<PrimitiveFieldsSaga, int>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<PrimitiveFieldsSaga, int>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<PrimitiveFieldsSaga>, PrimitiveFieldsSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<PrimitiveFieldsSaga, int>, SagaManager<PrimitiveFieldsSaga, int>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, PrimitiveFieldsSaga_Started_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithPrimitiveFieldsSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithPrimitiveFieldsSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddPrimitiveFieldsSaga(this ISagaBuilder builder)
        => builder.WithPrimitiveFieldsSaga();
}

internal sealed class PrimitiveFieldsSagaCompensationDispatcher : ISagaCompensationDispatcher<PrimitiveFieldsSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public PrimitiveFieldsSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(PrimitiveFieldsSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(PrimitiveFieldsSagaFsm.Trigger.CompensateDone);
    }
}
