//HintName: PrimitiveFieldsSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class PrimitiveFieldsSagaCorrelationDispatch
{
    private static readonly PrimitiveFieldsSaga _probe = new PrimitiveFieldsSaga();

    public static int GetKey(global::Sample.Started e) => _probe.Correlation(e);
}
