//HintName: PrimitiveFieldsSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class PrimitiveFieldsSaga
{
    public PrimitiveFieldsSagaFsm Fsm { get; } = new PrimitiveFieldsSagaFsm();
}
