//HintName: App.OrderSaga.Handler.App.Paid.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace App;

internal sealed class OrderSaga_Paid_Handler : INotificationHandler<global::App.Paid>
{
    // Scope-per-attempt: ISagaStore<TSaga,TKey> and ISagaCommandDispatcher
    // are resolved from a fresh IServiceScope inside the retry loop. On a
    // DbUpdateException / DbUpdateConcurrencyException catch, the scope's
    // DbContext (and any tracked outbox row added by OutboxSagaCommandDispatcher)
    // is disposed before the next attempt — so a retry that eventually succeeds
    // commits exactly ONE outbox row (the winning attempt's). The lock manager,
    // retry options, and logger live outside the per-attempt scope because the
    // lock must be held across the whole retry loop and the others have no
    // per-attempt state.
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly SagaLockManager<int> _locks;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<OrderSaga_Paid_Handler> _log;

    public OrderSaga_Paid_Handler(IServiceScopeFactory scopeFactory, SagaLockManager<int> locks, SagaRetryOptions retry, ILogger<OrderSaga_Paid_Handler> log)
    {
        _scopeFactory = scopeFactory;
        _locks = locks;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::App.Paid @event, CancellationToken ct)
    {
        var key = OrderSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            using var scope = _scopeFactory.CreateScope();
            var store = scope.ServiceProvider.GetRequiredService<ISagaStore<OrderSaga, int>>();
            var dispatcher = scope.ServiceProvider.GetRequiredService<ISagaCommandDispatcher>();
            try
            {
                var saga = await store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
                if (!saga.Fsm.TryFire(OrderSagaFsm.Trigger.Paid))
                {
                    _log.LogDebug("Saga {Saga}: late Paid for key {Key}; ignored", "OrderSaga", key);
                    return;
                }

                var cmd = saga.Second(@event);
                await dispatcher.DispatchAsync(cmd, ct).ConfigureAwait(false);

                saga.Fsm.TryFire(OrderSagaFsm.Trigger.Complete);
                await store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsBackendConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}", "OrderSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsBackendConflict(ex))
            {
                throw new SagaConcurrencyException("OrderSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsBackendConflict(Exception ex)
    {
        // Any store signals a retryable conflict by implementing
        // ISagaConcurrencyConflict, so no backend type names appear here.
        return ex is global::ZeroAlloc.Saga.ISagaConcurrencyConflict;
    }
}
