//HintName: MultiFieldOrderSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class MultiFieldOrderSagaCorrelationDispatch
{
    private static readonly MultiFieldOrderSaga _probe = new MultiFieldOrderSaga();

    public static int GetKey(global::Sample.Started e) => _probe.Correlation(e);
}
