//HintName: EnumFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class EnumFieldSagaBuilderExtensions
{
    public static ISagaBuilder AddEnumFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<EnumFieldSaga, int>, InMemorySagaStore<EnumFieldSaga, int>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<EnumFieldSaga, int>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<EnumFieldSaga>, EnumFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<EnumFieldSaga, int>, SagaManager<EnumFieldSaga, int>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, EnumFieldSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class EnumFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<EnumFieldSaga>
{
    private readonly IMediator _mediator;
    public EnumFieldSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(EnumFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(EnumFieldSagaFsm.Trigger.CompensateDone);
    }
}
