//HintName: App.OrderSaga.BuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace App;

public static class OrderSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="OrderSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithOrderSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<OrderSaga, int>, InMemorySagaStore<OrderSaga, int>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<OrderSaga, int>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<OrderSaga>, OrderSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<OrderSaga, int>, SagaManager<OrderSaga, int>>();
        global::ZeroAlloc.Saga.SagaCommandSourceBuilderExtensions.AddCommandSource(builder, global::ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource.Instance, typeof(OrderSaga));

        builder.Services.AddTransient<INotificationHandler<global::Complete>, OrderSaga_global_Complete_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::App.Paid>, OrderSaga_Paid_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::App.CompensateDone>, OrderSaga_App_CompensateDone_Handler>();
        return builder;
    }
}

internal sealed class OrderSagaCompensationDispatcher : ISagaCompensationDispatcher<OrderSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public OrderSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(OrderSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            case OrderSagaFsm.State.Step2:
                await _dispatcher.DispatchAsync(saga.Undo(), ct).ConfigureAwait(false);
                break;
            case OrderSagaFsm.State.Step1:
                await _dispatcher.DispatchAsync(saga.Undo(), ct).ConfigureAwait(false);
                break;
            default: break;
        }
        saga.Fsm.TryFire(OrderSagaFsm.Trigger.CompensateDone);
    }
}
