//HintName: ThreeStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class ThreeStepSagaBuilderExtensions
{
    public static ISagaBuilder AddThreeStepSaga(this ISagaBuilder builder)
    {
        builder.Services.TryAddSingleton<ISagaStore<ThreeStepSaga, global::Sample.OrderId>, InMemorySagaStore<ThreeStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<ThreeStepSaga>, ThreeStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<ThreeStepSaga, global::Sample.OrderId>, SagaManager<ThreeStepSaga, global::Sample.OrderId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, ThreeStepSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, ThreeStepSaga_StockReserved_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentCharged>, ThreeStepSaga_PaymentCharged_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentDeclined>, ThreeStepSaga_PaymentDeclined_Handler>();
        return builder;
    }
}

internal sealed class ThreeStepSagaCompensationDispatcher : ISagaCompensationDispatcher<ThreeStepSaga>
{
    private readonly IMediator _mediator;
    public ThreeStepSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(ThreeStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            case ThreeStepSagaFsm.State.Step3:
                await _mediator.Send(saga.Refund(), ct).ConfigureAwait(false);
                await _mediator.Send(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            case ThreeStepSagaFsm.State.Step2:
                await _mediator.Send(saga.Refund(), ct).ConfigureAwait(false);
                await _mediator.Send(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            case ThreeStepSagaFsm.State.Step1:
                await _mediator.Send(saga.CancelReservation(), ct).ConfigureAwait(false);
                break;
            default: break;
        }
        saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.CompensateDone);
    }
}
