//HintName: AuditSaga_OrderShipped_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class AuditSaga_OrderShipped_Handler : INotificationHandler<global::Sample.OrderShipped>
{
    private readonly ISagaStore<AuditSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<AuditSaga_OrderShipped_Handler> _log;

    public AuditSaga_OrderShipped_Handler(ISagaStore<AuditSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, IMediator mediator, ILogger<AuditSaga_OrderShipped_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.OrderShipped @event, CancellationToken ct)
    {
        var key = AuditSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
        if (!saga.Fsm.TryFire(AuditSagaFsm.Trigger.OrderShipped))
        {
            _log.LogDebug("Saga {Saga}: late OrderShipped for key {Key}; ignored", "AuditSaga", key);
            return;
        }

        var cmd = saga.Audit(@event);
        await _mediator.Send(cmd, ct).ConfigureAwait(false);

        saga.Fsm.TryFire(AuditSagaFsm.Trigger.Complete);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
