//HintName: MultiFailureSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class MultiFailureSaga
{
    public MultiFailureSagaFsm Fsm { get; } = new MultiFailureSagaFsm();
}
