//HintName: App.OrderSaga.Fsm.g.cs
// <auto-generated/>
#nullable enable

namespace App;

public partial class OrderSagaFsm
{
    public enum State { NotStarted, Step1, Step2, Step3, Completed, Compensating, Compensated }
    public enum Trigger { A_Placed, B_Placed, Shipped, A_Failed, B_Failed, Complete, CompensateDone }

    private State _state = State.NotStarted;
    public State Current => _state;

    public bool TryFire(Trigger trigger)
    {
        var next = (_state, trigger) switch
        {
            (State.NotStarted, Trigger.A_Placed) => (State?)State.Step1,
            (State.Step1, Trigger.B_Placed) => (State?)State.Step2,
            (State.Step2, Trigger.Shipped) => (State?)State.Step3,
            (State.Step3, Trigger.Complete) => (State?)State.Completed,
            (State.Step1, Trigger.A_Failed) => (State?)State.Compensating,
            (State.Step2, Trigger.B_Failed) => (State?)State.Compensating,
            (State.Compensating, Trigger.CompensateDone) => (State?)State.Compensated,
            _ => (State?)null
        };

        if (next is null) return false;
        _state = next.Value;
        return true;
    }

    public void SetCurrentState(State state) => _state = state;
}
