//HintName: App.OrderSaga.CorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace App;

internal static class OrderSagaCorrelationDispatch
{
    private static readonly OrderSaga _probe = new OrderSaga();

    public static int GetKey(global::A.Placed e) => _probe.Key(e);
    public static int GetKey(global::B.Placed e) => _probe.Key(e);
    public static int GetKey(global::A.Failed e) => _probe.Key(e);
    public static int GetKey(global::B.Failed e) => _probe.Key(e);
    public static int GetKey(global::App.Shipped e) => _probe.Key(e);
}
