//HintName: App.OrderSaga.CorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace App;

internal static class OrderSagaCorrelationDispatch
{
    private static readonly OrderSaga _probe = new OrderSaga();

    public static int GetKey(global::Complete e) => _probe.Key(e);
    public static int GetKey(global::App.CompensateDone e) => _probe.Key(e);
    public static int GetKey(global::App.Paid e) => _probe.Key(e);
}
