//HintName: ThreeStepSaga_PaymentCharged_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class ThreeStepSaga_PaymentCharged_Handler : INotificationHandler<global::Sample.PaymentCharged>
{
    private readonly ISagaStore<ThreeStepSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<ThreeStepSaga_PaymentCharged_Handler> _log;

    public ThreeStepSaga_PaymentCharged_Handler(ISagaStore<ThreeStepSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, IMediator mediator, ILogger<ThreeStepSaga_PaymentCharged_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.PaymentCharged @event, CancellationToken ct)
    {
        var key = ThreeStepSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
        if (!saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.PaymentCharged))
        {
            _log.LogDebug("Saga {Saga}: late PaymentCharged for key {Key}; ignored", "ThreeStepSaga", key);
            return;
        }

        var cmd = saga.Ship(@event);
        await _mediator.Send(cmd, ct).ConfigureAwait(false);

        saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.Complete);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
