//HintName: StateFieldSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class StateFieldSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        __w.WriteInt32(this.OrderId.V);
        __w.WriteDecimal(this.Total);
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.StateFieldSaga", SagaStateVersion, __version);
        this.OrderId = new global::Sample.OrderId(__r.ReadInt32());
        this.Total = __r.ReadDecimal();
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<StateFieldSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
