//HintName: NullableFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class NullableFieldSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="NullableFieldSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithNullableFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<NullableFieldSaga, int>, InMemorySagaStore<NullableFieldSaga, int>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<NullableFieldSaga, int>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<NullableFieldSaga>, NullableFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<NullableFieldSaga, int>, SagaManager<NullableFieldSaga, int>>();
        global::ZeroAlloc.Saga.SagaCommandSourceBuilderExtensions.AddCommandSource(builder, global::ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource.Instance, typeof(NullableFieldSaga));

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, NullableFieldSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class NullableFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<NullableFieldSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public NullableFieldSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(NullableFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(NullableFieldSagaFsm.Trigger.CompensateDone);
    }
}
