//HintName: ExcludedFieldSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class ExcludedFieldSagaCorrelationDispatch
{
    private static readonly ExcludedFieldSaga _probe = new ExcludedFieldSaga();

    public static int GetKey(global::Sample.Started e) => _probe.Correlation(e);
}
