//HintName: ExcludedFieldSaga_Started_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class ExcludedFieldSaga_Started_Handler : INotificationHandler<global::Sample.Started>
{
    private readonly ISagaStore<ExcludedFieldSaga, int> _store;
    private readonly SagaLockManager<int> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<ExcludedFieldSaga_Started_Handler> _log;

    public ExcludedFieldSaga_Started_Handler(ISagaStore<ExcludedFieldSaga, int> store, SagaLockManager<int> locks, IMediator mediator, ILogger<ExcludedFieldSaga_Started_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.Started @event, CancellationToken ct)
    {
        var key = ExcludedFieldSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
        if (!saga.Fsm.TryFire(ExcludedFieldSagaFsm.Trigger.Started))
        {
            _log.LogDebug("Saga {Saga}: late Started for key {Key}; ignored", "ExcludedFieldSaga", key);
            return;
        }

        var cmd = saga.Step1(@event);
        await _mediator.Send(cmd, ct).ConfigureAwait(false);

        saga.Fsm.TryFire(ExcludedFieldSagaFsm.Trigger.Complete);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
