//HintName: MediatorSagaCommandDispatcher.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace ZeroAlloc.Saga.Generated;

/// <summary>
/// Default <see cref="ISagaCommandDispatcher"/> emitted by the Saga generator.
/// Forwards to <see cref="IMediator.Send"/> via a switch on the runtime command type.
/// Replaced by <c>ZeroAlloc.Saga.Outbox.WithOutbox()</c> for transactional dispatch.
/// </summary>
internal sealed class MediatorSagaCommandDispatcher : ISagaCommandDispatcher
{
    private readonly IMediator _mediator;
    public MediatorSagaCommandDispatcher(IMediator mediator) => _mediator = mediator;

    public ValueTask DispatchAsync<TCommand>(TCommand cmd, CancellationToken ct)
        where TCommand : IRequest<Unit>
    {
        return cmd switch
        {
            global::Sample.ChargeCommand c => Forward(_mediator.Send(c, ct)),
            _ => throw new InvalidOperationException(
                $"MediatorSagaCommandDispatcher: no dispatch arm for command type '{typeof(TCommand).FullName}'. The Saga generator did not emit a Send call for this type — ensure the type is referenced from a [Step] method's return type in this compilation.")
        };

        static ValueTask Forward(ValueTask<Unit> task)
        {
            if (task.IsCompletedSuccessfully) { _ = task.Result; return ValueTask.CompletedTask; }
            return ConvertAsync(task);

            static async ValueTask ConvertAsync(ValueTask<Unit> t) => await t.ConfigureAwait(false);
        }
    }
}
