//HintName: ThreeStepSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class ThreeStepSagaCorrelationDispatch
{
    private static readonly ThreeStepSaga _probe = new ThreeStepSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.StockReserved e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.PaymentCharged e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.PaymentDeclined e) => _probe.Correlation(e);
}
