//HintName: PrimitiveFieldsSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class PrimitiveFieldsSagaBuilderExtensions
{
    public static ISagaBuilder AddPrimitiveFieldsSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<PrimitiveFieldsSaga, global::int>, InMemorySagaStore<PrimitiveFieldsSaga, global::int>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<PrimitiveFieldsSaga, global::int>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<PrimitiveFieldsSaga>, PrimitiveFieldsSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<PrimitiveFieldsSaga, global::int>, SagaManager<PrimitiveFieldsSaga, global::int>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, PrimitiveFieldsSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class PrimitiveFieldsSagaCompensationDispatcher : ISagaCompensationDispatcher<PrimitiveFieldsSaga>
{
    private readonly IMediator _mediator;
    public PrimitiveFieldsSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(PrimitiveFieldsSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(PrimitiveFieldsSagaFsm.Trigger.CompensateDone);
    }
}
