//HintName: GeneratedSagaCommandSource.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace ZeroAlloc.Saga.Generated;

/// <summary>
/// This assembly's saga commands. Every generator-emitted <c>With{Saga}()</c> in this assembly
/// adds it to the saga builder, so commands are dispatched through this assembly's
/// <see cref="IMediator"/> even when other assemblies declare sagas too.
/// </summary>
internal sealed class GeneratedSagaCommandSource : SagaCommandSource
{
    internal static readonly GeneratedSagaCommandSource Instance = new();

    private static readonly Type[] s_commandTypes =
    {
        typeof(global::Sample.AuditCommand),
        typeof(global::Sample.ReserveCommand),
    };

    // Sample.AuditSaga
    private static readonly Type[] s_sagaCommandTypes0 =
    {
        typeof(global::Sample.AuditCommand),
    };

    // Sample.FulfillmentSaga
    private static readonly Type[] s_sagaCommandTypes1 =
    {
        typeof(global::Sample.ReserveCommand),
    };

    private GeneratedSagaCommandSource()
    {
    }

    public override IReadOnlyList<Type> CommandTypes => s_commandTypes;

    public override IReadOnlyList<Type> GetCommandTypes(Type sagaType)
    {
        if (sagaType == typeof(global::Sample.AuditSaga)) return s_sagaCommandTypes0;
        if (sagaType == typeof(global::Sample.FulfillmentSaga)) return s_sagaCommandTypes1;
        return Array.Empty<Type>();
    }

    public override ISagaCommandDispatcher CreateDispatcher(IServiceProvider services)
        => new MediatorSagaCommandDispatcher(services.GetRequiredService<IMediator>());
}
