//HintName: MultiFieldOrderSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class MultiFieldOrderSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="MultiFieldOrderSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithMultiFieldOrderSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<MultiFieldOrderSaga, int>, InMemorySagaStore<MultiFieldOrderSaga, int>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<MultiFieldOrderSaga, int>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<MultiFieldOrderSaga>, MultiFieldOrderSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<MultiFieldOrderSaga, int>, SagaManager<MultiFieldOrderSaga, int>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, MultiFieldOrderSaga_Started_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithMultiFieldOrderSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithMultiFieldOrderSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddMultiFieldOrderSaga(this ISagaBuilder builder)
        => builder.WithMultiFieldOrderSaga();
}

internal sealed class MultiFieldOrderSagaCompensationDispatcher : ISagaCompensationDispatcher<MultiFieldOrderSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public MultiFieldOrderSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(MultiFieldOrderSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(MultiFieldOrderSagaFsm.Trigger.CompensateDone);
    }
}
