//HintName: AuditSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class AuditSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="AuditSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithAuditSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<AuditSaga, global::Sample.OrderId>, InMemorySagaStore<AuditSaga, global::Sample.OrderId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<AuditSaga, global::Sample.OrderId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<AuditSaga>, AuditSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<AuditSaga, global::Sample.OrderId>, SagaManager<AuditSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderShipped>, AuditSaga_OrderShipped_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithAuditSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithAuditSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddAuditSaga(this ISagaBuilder builder)
        => builder.WithAuditSaga();
}

internal sealed class AuditSagaCompensationDispatcher : ISagaCompensationDispatcher<AuditSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public AuditSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(AuditSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(AuditSagaFsm.Trigger.CompensateDone);
    }
}
