//HintName: MultiFieldOrderSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class MultiFieldOrderSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        __w.WriteInt32(this.A);
        __w.WriteString(this.B);
        __w.WriteBoolean(this.C);
        __w.WriteGuid(this.D);
        __w.WriteDecimal(this.E);
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.MultiFieldOrderSaga", SagaStateVersion, __version);
        this.A = __r.ReadInt32();
        this.B = __r.ReadString()!;
        this.C = __r.ReadBoolean();
        this.D = __r.ReadGuid();
        this.E = __r.ReadDecimal();
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<MultiFieldOrderSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
