//HintName: ThreeStepSagaFsm.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class ThreeStepSagaFsm
{
    public enum State { NotStarted, Step1, Step2, Step3, Completed, Compensating, Compensated }
    public enum Trigger { OrderPlaced, StockReserved, PaymentCharged, PaymentDeclined, Complete, CompensateDone }

    private State _state = State.NotStarted;
    public State Current => _state;

    public bool TryFire(Trigger trigger)
    {
        var next = (_state, trigger) switch
        {
            (State.NotStarted, Trigger.OrderPlaced) => (State?)State.Step1,
            (State.Step1, Trigger.StockReserved) => (State?)State.Step2,
            (State.Step2, Trigger.PaymentCharged) => (State?)State.Step3,
            (State.Step3, Trigger.Complete) => (State?)State.Completed,
            (State.Step2, Trigger.PaymentDeclined) => (State?)State.Compensating,
            (State.Compensating, Trigger.CompensateDone) => (State?)State.Compensated,
            _ => (State?)null
        };

        if (next is null) return false;
        _state = next.Value;
        return true;
    }
}
