//HintName: EnumFieldSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class EnumFieldSagaCorrelationDispatch
{
    private static readonly EnumFieldSaga _probe = new EnumFieldSaga();

    public static int GetKey(global::Sample.Started e) => _probe.Correlation(e);
}
