//HintName: ThreeStepSaga_PaymentDeclined_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class ThreeStepSaga_PaymentDeclined_Handler : INotificationHandler<global::Sample.PaymentDeclined>
{
    // Scope-per-attempt: see the same-named comment in the forward handler.
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<ThreeStepSaga_PaymentDeclined_Handler> _log;

    public ThreeStepSaga_PaymentDeclined_Handler(IServiceScopeFactory scopeFactory, SagaLockManager<global::Sample.OrderId> locks, SagaRetryOptions retry, ILogger<ThreeStepSaga_PaymentDeclined_Handler> log)
    {
        _scopeFactory = scopeFactory;
        _locks = locks;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.PaymentDeclined @event, CancellationToken ct)
    {
        // Resolve the correlation key for this failure event.
        var key = ThreeStepSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            using var scope = _scopeFactory.CreateScope();
            var store = scope.ServiceProvider.GetRequiredService<ISagaStore<ThreeStepSaga, global::Sample.OrderId>>();
            var dispatcher = scope.ServiceProvider.GetRequiredService<ISagaCommandDispatcher>();
            try
            {
                var saga = await store.TryLoadAsync(key, ct).ConfigureAwait(false);
                if (saga is null)
                {
                    _log.LogWarning("Saga {Saga}: orphan PaymentDeclined for key {Key}; no instance to compensate", "ThreeStepSaga", key);
                    return;
                }

                var stateAtFailure = saga.Fsm.Current;
                if (!saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.PaymentDeclined))
                {
                    _log.LogDebug("Saga {Saga}: PaymentDeclined not valid in state {State} for key {Key}; ignored", "ThreeStepSaga", stateAtFailure, key);
                    return;
                }

                // Reverse-cascade compensation: walk back from stateAtFailure to Step1.
                // Re-dispatch contract: if RemoveAsync below throws an EF Core conflict
                // (third party deleted/updated row mid-compensation), the surrounding
                // retry loop re-enters this try block. On retry, TryLoadAsync may return
                // null (just-deleted) and the handler returns silently; otherwise the
                // compensation commands below may be dispatched a second time. The
                // "idempotency is the user's responsibility" contract (ZASAGA015) covers this.
                switch (stateAtFailure)
                {
                    case ThreeStepSagaFsm.State.Step2:
                        await dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                        await dispatcher.DispatchAsync(saga.CancelReservation(), ct).ConfigureAwait(false);
                        break;
                    default: break;
                }

                saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.CompensateDone);
                await store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsBackendConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on compensation for key {Key}, retry {Attempt}/{Max}", "ThreeStepSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsBackendConflict(ex))
            {
                throw new SagaConcurrencyException("ThreeStepSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsBackendConflict(Exception ex)
    {
        var typeName = ex.GetType().FullName;
        return typeName == "Microsoft.EntityFrameworkCore.DbUpdateException"
            || typeName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException"
            || typeName == "ZeroAlloc.Saga.Redis.RedisSagaConcurrencyException";
    }
}
