//HintName: FulfillmentSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class FulfillmentSaga
{
    public FulfillmentSagaFsm Fsm { get; } = new FulfillmentSagaFsm();
}
