//HintName: StateFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class StateFieldSagaBuilderExtensions
{
    public static ISagaBuilder AddStateFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.TryAddSingleton<ISagaStore<StateFieldSaga, global::Sample.OrderId>, InMemorySagaStore<StateFieldSaga, global::Sample.OrderId>>();
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<StateFieldSaga>, StateFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<StateFieldSaga, global::Sample.OrderId>, SagaManager<StateFieldSaga, global::Sample.OrderId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, StateFieldSaga_OrderPlaced_Handler>();
        return builder;
    }
}

internal sealed class StateFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<StateFieldSaga>
{
    private readonly IMediator _mediator;
    public StateFieldSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(StateFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(StateFieldSagaFsm.Trigger.CompensateDone);
    }
}
