//HintName: MultiFieldOrderSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class MultiFieldOrderSaga
{
    public MultiFieldOrderSagaFsm Fsm { get; } = new MultiFieldOrderSagaFsm();
}
