//HintName: Sample.MultiFieldOrderSaga.BuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class MultiFieldOrderSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="MultiFieldOrderSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithMultiFieldOrderSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<MultiFieldOrderSaga, int>, InMemorySagaStore<MultiFieldOrderSaga, int>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<MultiFieldOrderSaga, int>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<MultiFieldOrderSaga>, MultiFieldOrderSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<MultiFieldOrderSaga, int>, SagaManager<MultiFieldOrderSaga, int>>();
        global::ZeroAlloc.Saga.SagaCommandSourceBuilderExtensions.AddCommandSource(builder, global::ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource.Instance, typeof(MultiFieldOrderSaga));

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, MultiFieldOrderSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class MultiFieldOrderSagaCompensationDispatcher : ISagaCompensationDispatcher<MultiFieldOrderSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public MultiFieldOrderSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(MultiFieldOrderSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(MultiFieldOrderSagaFsm.Trigger.CompensateDone);
    }
}
