//HintName: TypedIdFieldSaga_Activated_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class TypedIdFieldSaga_Activated_Handler : INotificationHandler<global::Sample.Activated>
{
    private readonly ISagaStore<TypedIdFieldSaga, global::Sample.CustomerId> _store;
    private readonly SagaLockManager<global::Sample.CustomerId> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<TypedIdFieldSaga_Activated_Handler> _log;

    public TypedIdFieldSaga_Activated_Handler(ISagaStore<TypedIdFieldSaga, global::Sample.CustomerId> store, SagaLockManager<global::Sample.CustomerId> locks, IMediator mediator, ILogger<TypedIdFieldSaga_Activated_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.Activated @event, CancellationToken ct)
    {
        var key = TypedIdFieldSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
        if (!saga.Fsm.TryFire(TypedIdFieldSagaFsm.Trigger.Activated))
        {
            _log.LogDebug("Saga {Saga}: late Activated for key {Key}; ignored", "TypedIdFieldSaga", key);
            return;
        }

        var cmd = saga.Greet(@event);
        await _mediator.Send(cmd, ct).ConfigureAwait(false);

        saga.Fsm.TryFire(TypedIdFieldSagaFsm.Trigger.Complete);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
