//HintName: MultiFailureSaga_PaymentFailed_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class MultiFailureSaga_PaymentFailed_Handler : INotificationHandler<global::Sample.PaymentFailed>
{
    private readonly ISagaStore<MultiFailureSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly ISagaCommandDispatcher _dispatcher;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<MultiFailureSaga_PaymentFailed_Handler> _log;

    public MultiFailureSaga_PaymentFailed_Handler(ISagaStore<MultiFailureSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, ISagaCommandDispatcher dispatcher, SagaRetryOptions retry, ILogger<MultiFailureSaga_PaymentFailed_Handler> log)
    {
        _store = store;
        _locks = locks;
        _dispatcher = dispatcher;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.PaymentFailed @event, CancellationToken ct)
    {
        // Resolve the correlation key for this failure event.
        var key = MultiFailureSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            try
            {
                var saga = await _store.TryLoadAsync(key, ct).ConfigureAwait(false);
                if (saga is null)
                {
                    _log.LogWarning("Saga {Saga}: orphan PaymentFailed for key {Key}; no instance to compensate", "MultiFailureSaga", key);
                    return;
                }

                var stateAtFailure = saga.Fsm.Current;
                if (!saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.PaymentFailed))
                {
                    _log.LogDebug("Saga {Saga}: PaymentFailed not valid in state {State} for key {Key}; ignored", "MultiFailureSaga", stateAtFailure, key);
                    return;
                }

                // Reverse-cascade compensation: walk back from stateAtFailure to Step1.
                // Re-dispatch contract: if RemoveAsync below throws an EF Core conflict
                // (third party deleted/updated row mid-compensation), the surrounding
                // retry loop re-enters this try block. On retry, TryLoadAsync may return
                // null (just-deleted) and the handler returns silently; otherwise the
                // compensation commands below may be dispatched a second time. The
                // "idempotency is the user's responsibility" contract (ZASAGA015) covers this.
                switch (stateAtFailure)
                {
                    case MultiFailureSagaFsm.State.Step2:
                        await _dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                        await _dispatcher.DispatchAsync(saga.CancelReserve(), ct).ConfigureAwait(false);
                        break;
                    default: break;
                }

                saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.CompensateDone);
                await _store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on compensation for key {Key}, retry {Attempt}/{Max}", "MultiFailureSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsEfCoreConflict(ex))
            {
                throw new SagaConcurrencyException("MultiFailureSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsEfCoreConflict(Exception ex)
    {
        var typeName = ex.GetType().FullName;
        return typeName == "Microsoft.EntityFrameworkCore.DbUpdateException"
            || typeName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException";
    }
}
