//HintName: TypedIdFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class TypedIdFieldSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="TypedIdFieldSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithTypedIdFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<TypedIdFieldSaga, global::Sample.CustomerId>, InMemorySagaStore<TypedIdFieldSaga, global::Sample.CustomerId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<TypedIdFieldSaga, global::Sample.CustomerId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.CustomerId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<TypedIdFieldSaga>, TypedIdFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<TypedIdFieldSaga, global::Sample.CustomerId>, SagaManager<TypedIdFieldSaga, global::Sample.CustomerId>>();
        global::ZeroAlloc.Saga.SagaCommandSourceBuilderExtensions.AddCommandSource(builder, global::ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource.Instance);

        builder.Services.AddTransient<INotificationHandler<global::Sample.Activated>, TypedIdFieldSaga_Activated_Handler>();
        return builder;
    }
}

internal sealed class TypedIdFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<TypedIdFieldSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public TypedIdFieldSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(TypedIdFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(TypedIdFieldSagaFsm.Trigger.CompensateDone);
    }
}
