//HintName: ThreeStepSaga_PaymentCharged_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class ThreeStepSaga_PaymentCharged_Handler : INotificationHandler<global::Sample.PaymentCharged>
{
    // Scope-per-attempt: ISagaStore<TSaga,TKey> and ISagaCommandDispatcher
    // are resolved from a fresh IServiceScope inside the retry loop. On a
    // DbUpdateException / DbUpdateConcurrencyException catch, the scope's
    // DbContext (and any tracked outbox row added by OutboxSagaCommandDispatcher)
    // is disposed before the next attempt — so a retry that eventually succeeds
    // commits exactly ONE outbox row (the winning attempt's). The lock manager,
    // retry options, and logger live outside the per-attempt scope because the
    // lock must be held across the whole retry loop and the others have no
    // per-attempt state.
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<ThreeStepSaga_PaymentCharged_Handler> _log;

    public ThreeStepSaga_PaymentCharged_Handler(IServiceScopeFactory scopeFactory, SagaLockManager<global::Sample.OrderId> locks, SagaRetryOptions retry, ILogger<ThreeStepSaga_PaymentCharged_Handler> log)
    {
        _scopeFactory = scopeFactory;
        _locks = locks;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.PaymentCharged @event, CancellationToken ct)
    {
        var key = ThreeStepSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            using var scope = _scopeFactory.CreateScope();
            var store = scope.ServiceProvider.GetRequiredService<ISagaStore<ThreeStepSaga, global::Sample.OrderId>>();
            var dispatcher = scope.ServiceProvider.GetRequiredService<ISagaCommandDispatcher>();
            try
            {
                var saga = await store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
                if (!saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.PaymentCharged))
                {
                    _log.LogDebug("Saga {Saga}: late PaymentCharged for key {Key}; ignored", "ThreeStepSaga", key);
                    return;
                }

                var cmd = saga.Ship(@event);
                await dispatcher.DispatchAsync(cmd, ct).ConfigureAwait(false);

                saga.Fsm.TryFire(ThreeStepSagaFsm.Trigger.Complete);
                await store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}", "ThreeStepSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsEfCoreConflict(ex))
            {
                throw new SagaConcurrencyException("ThreeStepSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsEfCoreConflict(Exception ex)
    {
        var typeName = ex.GetType().FullName;
        return typeName == "Microsoft.EntityFrameworkCore.DbUpdateException"
            || typeName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException";
    }
}
