//HintName: MultiFieldOrderSaga_Started_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class MultiFieldOrderSaga_Started_Handler : INotificationHandler<global::Sample.Started>
{
    private readonly ISagaStore<MultiFieldOrderSaga, int> _store;
    private readonly SagaLockManager<int> _locks;
    private readonly IMediator _mediator;
    private readonly SagaRetryOptions _retry;
    private readonly ILogger<MultiFieldOrderSaga_Started_Handler> _log;

    public MultiFieldOrderSaga_Started_Handler(ISagaStore<MultiFieldOrderSaga, int> store, SagaLockManager<int> locks, IMediator mediator, SagaRetryOptions retry, ILogger<MultiFieldOrderSaga_Started_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _retry = retry;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.Started @event, CancellationToken ct)
    {
        var key = MultiFieldOrderSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var attempts = 0;
        while (true)
        {
            try
            {
                var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);
                if (!saga.Fsm.TryFire(MultiFieldOrderSagaFsm.Trigger.Started))
                {
                    _log.LogDebug("Saga {Saga}: late Started for key {Key}; ignored", "MultiFieldOrderSaga", key);
                    return;
                }

                var cmd = saga.Step1(@event);
                await _mediator.Send(cmd, ct).ConfigureAwait(false);

                saga.Fsm.TryFire(MultiFieldOrderSagaFsm.Trigger.Complete);
                await _store.RemoveAsync(key, ct).ConfigureAwait(false);
                return;
            }
            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))
            {
                attempts++;
                _log.LogWarning("Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}", "MultiFieldOrderSaga", key, attempts, _retry.MaxRetryAttempts);
                var delay = _retry.UseExponentialBackoff
                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))
                    : _retry.RetryBaseDelay;
                await Task.Delay(delay, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (IsEfCoreConflict(ex))
            {
                throw new SagaConcurrencyException("MultiFieldOrderSaga", key.ToString() ?? string.Empty, attempts, ex);
            }
        }
    }

    private static bool IsEfCoreConflict(Exception ex)
    {
        var typeName = ex.GetType().FullName;
        return typeName == "Microsoft.EntityFrameworkCore.DbUpdateException"
            || typeName == "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException";
    }
}
