//HintName: PrimitiveFieldsSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class PrimitiveFieldsSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        __w.WriteInt32(this.Count);
        __w.WriteString(this.Name);
        __w.WriteBoolean(this.IsActive);
        __w.WriteDouble(this.Amount);
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.PrimitiveFieldsSaga", SagaStateVersion, __version);
        this.Count = __r.ReadInt32();
        this.Name = __r.ReadString()!;
        this.IsActive = __r.ReadBoolean();
        this.Amount = __r.ReadDouble();
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<PrimitiveFieldsSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
