//HintName: TypedIdFieldSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class TypedIdFieldSaga
{
    public TypedIdFieldSagaFsm Fsm { get; } = new TypedIdFieldSagaFsm();
}
