//HintName: NullableFieldSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class NullableFieldSagaCorrelationDispatch
{
    private static readonly NullableFieldSaga _probe = new NullableFieldSaga();

    public static int GetKey(global::Sample.Started e) => _probe.Correlation(e);
}
