//HintName: NullableFieldSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class NullableFieldSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        if (this.OptionalCount.HasValue) { __w.WriteBoolean(true); __w.WriteInt32(this.OptionalCount.Value); } else { __w.WriteBoolean(false); }
        if (this.LastSeen.HasValue) { __w.WriteBoolean(true); __w.WriteDateTime(this.LastSeen.Value); } else { __w.WriteBoolean(false); }
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.NullableFieldSaga", SagaStateVersion, __version);
        if (__r.ReadBoolean()) { int __nv_OptionalCount; __nv_OptionalCount = __r.ReadInt32(); this.OptionalCount = __nv_OptionalCount; } else { this.OptionalCount = null; }
        if (__r.ReadBoolean()) { global::System.DateTime __nv_LastSeen; __nv_LastSeen = __r.ReadDateTime(); this.LastSeen = __nv_LastSeen; } else { this.LastSeen = null; }
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<NullableFieldSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
