//HintName: NullableFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class NullableFieldSagaBuilderExtensions
{
    public static ISagaBuilder AddNullableFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<NullableFieldSaga, global::int>, InMemorySagaStore<NullableFieldSaga, global::int>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<NullableFieldSaga, global::int>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<NullableFieldSaga>, NullableFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<NullableFieldSaga, global::int>, SagaManager<NullableFieldSaga, global::int>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, NullableFieldSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class NullableFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<NullableFieldSaga>
{
    private readonly IMediator _mediator;
    public NullableFieldSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(NullableFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(NullableFieldSagaFsm.Trigger.CompensateDone);
    }
}
