//HintName: GeneratedSagaCommandSource.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace ZeroAlloc.Saga.Generated;

/// <summary>
/// This assembly's saga commands. Every generator-emitted <c>With{Saga}()</c> in this assembly
/// adds it to the saga builder, so commands are dispatched through this assembly's
/// <see cref="IMediator"/> even when other assemblies declare sagas too.
/// </summary>
internal sealed class GeneratedSagaCommandSource : SagaCommandSource
{
    internal static readonly GeneratedSagaCommandSource Instance = new();

    private static readonly Type[] s_commandTypes =
    {
        typeof(global::Sample.CancelReserveCommand),
        typeof(global::Sample.ChargeCommand),
        typeof(global::Sample.RefundCommand),
        typeof(global::Sample.ReserveCommand),
        typeof(global::Sample.ShipCommand),
    };

    private GeneratedSagaCommandSource()
    {
    }

    public override IReadOnlyList<Type> CommandTypes => s_commandTypes;

    public override ISagaCommandDispatcher CreateDispatcher(IServiceProvider services)
        => new MediatorSagaCommandDispatcher(services.GetRequiredService<IMediator>());
}
