//HintName: ThreeStepSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class ThreeStepSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.ThreeStepSaga", SagaStateVersion, __version);
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<ThreeStepSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
