//HintName: MultiFailureSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class MultiFailureSagaBuilderExtensions
{
    public static ISagaBuilder AddMultiFailureSaga(this ISagaBuilder builder)
    {
        builder.Services.TryAddSingleton<ISagaStore<MultiFailureSaga, global::Sample.OrderId>, InMemorySagaStore<MultiFailureSaga, global::Sample.OrderId>>();
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<MultiFailureSaga>, MultiFailureSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<MultiFailureSaga, global::Sample.OrderId>, SagaManager<MultiFailureSaga, global::Sample.OrderId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, MultiFailureSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, MultiFailureSaga_StockReserved_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.ChargedOk>, MultiFailureSaga_ChargedOk_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockOutOfStock>, MultiFailureSaga_StockOutOfStock_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentFailed>, MultiFailureSaga_PaymentFailed_Handler>();
        return builder;
    }
}

internal sealed class MultiFailureSagaCompensationDispatcher : ISagaCompensationDispatcher<MultiFailureSaga>
{
    private readonly IMediator _mediator;
    public MultiFailureSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(MultiFailureSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            case MultiFailureSagaFsm.State.Step3:
                await _mediator.Send(saga.Refund(), ct).ConfigureAwait(false);
                await _mediator.Send(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            case MultiFailureSagaFsm.State.Step2:
                await _mediator.Send(saga.Refund(), ct).ConfigureAwait(false);
                await _mediator.Send(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            case MultiFailureSagaFsm.State.Step1:
                await _mediator.Send(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            default: break;
        }
        saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.CompensateDone);
    }
}
