//HintName: AuditSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class AuditSagaCorrelationDispatch
{
    private static readonly AuditSaga _probe = new AuditSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderShipped e) => _probe.Correlation(e);
}
