//HintName: FulfillmentSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class FulfillmentSagaCorrelationDispatch
{
    private static readonly FulfillmentSaga _probe = new FulfillmentSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
}
