//HintName: MultiFailureSagaCorrelationDispatch.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

internal static class MultiFailureSagaCorrelationDispatch
{
    private static readonly MultiFailureSaga _probe = new MultiFailureSaga();

    public static global::Sample.OrderId GetKey(global::Sample.OrderPlaced e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.StockReserved e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.ChargedOk e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.StockOutOfStock e) => _probe.Correlation(e);
    public static global::Sample.OrderId GetKey(global::Sample.PaymentFailed e) => _probe.Correlation(e);
}
