//HintName: ExcludedFieldSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class ExcludedFieldSagaBuilderExtensions
{
    public static ISagaBuilder AddExcludedFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<ExcludedFieldSaga, int>, InMemorySagaStore<ExcludedFieldSaga, int>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<ExcludedFieldSaga, int>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<ExcludedFieldSaga>, ExcludedFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<ExcludedFieldSaga, int>, SagaManager<ExcludedFieldSaga, int>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, ExcludedFieldSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class ExcludedFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<ExcludedFieldSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public ExcludedFieldSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(ExcludedFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(ExcludedFieldSagaFsm.Trigger.CompensateDone);
    }
}
