//HintName: MultiFailureSaga_StockOutOfStock_Handler.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

internal sealed class MultiFailureSaga_StockOutOfStock_Handler : INotificationHandler<global::Sample.StockOutOfStock>
{
    private readonly ISagaStore<MultiFailureSaga, global::Sample.OrderId> _store;
    private readonly SagaLockManager<global::Sample.OrderId> _locks;
    private readonly IMediator _mediator;
    private readonly ILogger<MultiFailureSaga_StockOutOfStock_Handler> _log;

    public MultiFailureSaga_StockOutOfStock_Handler(ISagaStore<MultiFailureSaga, global::Sample.OrderId> store, SagaLockManager<global::Sample.OrderId> locks, IMediator mediator, ILogger<MultiFailureSaga_StockOutOfStock_Handler> log)
    {
        _store = store;
        _locks = locks;
        _mediator = mediator;
        _log = log;
    }

    public async ValueTask Handle(global::Sample.StockOutOfStock @event, CancellationToken ct)
    {
        // Resolve the correlation key for this failure event.
        var key = MultiFailureSagaCorrelationDispatch.GetKey(@event);
        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);

        var saga = await _store.TryLoadAsync(key, ct).ConfigureAwait(false);
        if (saga is null)
        {
            _log.LogWarning("Saga {Saga}: orphan StockOutOfStock for key {Key}; no instance to compensate", "MultiFailureSaga", key);
            return;
        }

        var stateAtFailure = saga.Fsm.Current;
        if (!saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.StockOutOfStock))
        {
            _log.LogDebug("Saga {Saga}: StockOutOfStock not valid in state {State} for key {Key}; ignored", "MultiFailureSaga", stateAtFailure, key);
            return;
        }

        // Reverse-cascade compensation: walk back from stateAtFailure to Step1.
        switch (stateAtFailure)
        {
            case MultiFailureSagaFsm.State.Step1:
                await _mediator.Send(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            default: break;
        }

        saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.CompensateDone);
        await _store.RemoveAsync(key, ct).ConfigureAwait(false);
    }
}
