//HintName: ExcludedFieldSaga.PersistableState.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class ExcludedFieldSaga : global::ZeroAlloc.Saga.ISagaPersistableState
{
    private const byte SagaStateVersion = 1;

    public byte[] Snapshot()
    {
        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);
        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);
        __w.WriteByte(SagaStateVersion);
        __w.WriteInt32(this.IncludedCount);
        return __buffer.WrittenSpan.ToArray();
    }

    public void Restore(global::System.ReadOnlySpan<byte> data)
    {
        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);
        var __version = __r.ReadByte();
        if (__version != SagaStateVersion)
            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException("Sample.ExcludedFieldSaga", SagaStateVersion, __version);
        this.IncludedCount = __r.ReadInt32();
    }

    public string CurrentFsmStateName => Fsm.Current.ToString();

    public void SetFsmStateFromName(string stateName)
    {
        var parsed = global::System.Enum.Parse<ExcludedFieldSagaFsm.State>(stateName);
        Fsm.SetCurrentState(parsed);
    }
}
