//HintName: Sample.EnumFieldSaga.BuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class EnumFieldSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="EnumFieldSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithEnumFieldSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<EnumFieldSaga, int>, InMemorySagaStore<EnumFieldSaga, int>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<EnumFieldSaga, int>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<int>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<EnumFieldSaga>, EnumFieldSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<EnumFieldSaga, int>, SagaManager<EnumFieldSaga, int>>();
        global::ZeroAlloc.Saga.SagaCommandSourceBuilderExtensions.AddCommandSource(builder, global::ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource.Instance, typeof(EnumFieldSaga));

        builder.Services.AddTransient<INotificationHandler<global::Sample.Started>, EnumFieldSaga_Started_Handler>();
        return builder;
    }
}

internal sealed class EnumFieldSagaCompensationDispatcher : ISagaCompensationDispatcher<EnumFieldSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public EnumFieldSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(EnumFieldSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(EnumFieldSagaFsm.Trigger.CompensateDone);
    }
}
