//HintName: TwoStepSagaFsm.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class TwoStepSagaFsm
{
    public enum State { NotStarted, Step1, Step2, Completed, Compensating, Compensated }
    public enum Trigger { OrderPlaced, StockReserved, Complete, CompensateDone }

    private State _state = State.NotStarted;
    public State Current => _state;

    public bool TryFire(Trigger trigger)
    {
        var next = (_state, trigger) switch
        {
            (State.NotStarted, Trigger.OrderPlaced) => (State?)State.Step1,
            (State.Step1, Trigger.StockReserved) => (State?)State.Step2,
            (State.Step2, Trigger.Complete) => (State?)State.Completed,
            (State.Compensating, Trigger.CompensateDone) => (State?)State.Compensated,
            _ => (State?)null
        };

        if (next is null) return false;
        _state = next.Value;
        return true;
    }

    public void SetCurrentState(State state) => _state = state;
}
