//HintName: MultiFailureSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class MultiFailureSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="MultiFailureSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithMultiFailureSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<MultiFailureSaga, global::Sample.OrderId>, InMemorySagaStore<MultiFailureSaga, global::Sample.OrderId>>();
        global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<MultiFailureSaga, global::Sample.OrderId>(builder);
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<MultiFailureSaga>, MultiFailureSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<MultiFailureSaga, global::Sample.OrderId>, SagaManager<MultiFailureSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, MultiFailureSaga_OrderPlaced_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockReserved>, MultiFailureSaga_StockReserved_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.ChargedOk>, MultiFailureSaga_ChargedOk_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.StockOutOfStock>, MultiFailureSaga_StockOutOfStock_Handler>();
        builder.Services.AddTransient<INotificationHandler<global::Sample.PaymentFailed>, MultiFailureSaga_PaymentFailed_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithMultiFailureSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithMultiFailureSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddMultiFailureSaga(this ISagaBuilder builder)
        => builder.WithMultiFailureSaga();
}

internal sealed class MultiFailureSagaCompensationDispatcher : ISagaCompensationDispatcher<MultiFailureSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public MultiFailureSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(MultiFailureSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            case MultiFailureSagaFsm.State.Step3:
                await _dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                await _dispatcher.DispatchAsync(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            case MultiFailureSagaFsm.State.Step2:
                await _dispatcher.DispatchAsync(saga.Refund(), ct).ConfigureAwait(false);
                await _dispatcher.DispatchAsync(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            case MultiFailureSagaFsm.State.Step1:
                await _dispatcher.DispatchAsync(saga.CancelReserve(), ct).ConfigureAwait(false);
                break;
            default: break;
        }
        saga.Fsm.TryFire(MultiFailureSagaFsm.Trigger.CompensateDone);
    }
}
