//HintName: SingleStepSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class SingleStepSagaBuilderExtensions
{
    public static ISagaBuilder AddSingleStepSaga(this ISagaBuilder builder)
    {
        builder.Services.TryAddSingleton<ISagaStore<SingleStepSaga, global::Sample.OrderId>, InMemorySagaStore<SingleStepSaga, global::Sample.OrderId>>();
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<SingleStepSaga>, SingleStepSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<SingleStepSaga, global::Sample.OrderId>, SagaManager<SingleStepSaga, global::Sample.OrderId>>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, SingleStepSaga_OrderPlaced_Handler>();
        return builder;
    }
}

internal sealed class SingleStepSagaCompensationDispatcher : ISagaCompensationDispatcher<SingleStepSaga>
{
    private readonly IMediator _mediator;
    public SingleStepSagaCompensationDispatcher(IMediator mediator) => _mediator = mediator;

    public async ValueTask CompensateAsync(SingleStepSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(SingleStepSagaFsm.Trigger.CompensateDone);
    }
}
