//HintName: NullableFieldSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class NullableFieldSaga
{
    public NullableFieldSagaFsm Fsm { get; } = new NullableFieldSagaFsm();
}
