//HintName: FulfillmentSagaBuilderExtensions.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using ZeroAlloc.Mediator;
using ZeroAlloc.Saga;

namespace Sample;

public static class FulfillmentSagaBuilderExtensions
{
    /// <summary>
    /// Registers <see cref="FulfillmentSaga"/>'s store, lock manager,
    /// saga manager, compensation dispatcher, and notification handlers.
    /// </summary>
    public static ISagaBuilder WithFulfillmentSaga(this ISagaBuilder builder)
    {
        builder.Services.AddMediator();
        builder.Services.TryAddSingleton<ISagaStore<FulfillmentSaga, global::Sample.OrderId>, InMemorySagaStore<FulfillmentSaga, global::Sample.OrderId>>();
        if (builder.IsEfCoreBackend)
        {
            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<FulfillmentSaga, global::Sample.OrderId>(builder);
        }
        builder.Services.TryAddSingleton<SagaLockManager<global::Sample.OrderId>>();
        builder.Services.TryAddTransient<ISagaCompensationDispatcher<FulfillmentSaga>, FulfillmentSagaCompensationDispatcher>();
        builder.Services.TryAddTransient<ISagaManager<FulfillmentSaga, global::Sample.OrderId>, SagaManager<FulfillmentSaga, global::Sample.OrderId>>();
        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();

        builder.Services.AddTransient<INotificationHandler<global::Sample.OrderPlaced>, FulfillmentSaga_OrderPlaced_Handler>();
        return builder;
    }

    /// <summary>
    /// Legacy alias for <see cref="WithFulfillmentSaga"/>.
    /// Will be removed in v2; use the <c>With</c>-prefixed name to align with the rest of the builder API.
    /// </summary>
    [System.Obsolete("Use WithFulfillmentSaga() instead. Will be removed in the next major.", DiagnosticId = "ZASAGA018")]
    public static ISagaBuilder AddFulfillmentSaga(this ISagaBuilder builder)
        => builder.WithFulfillmentSaga();
}

internal sealed class FulfillmentSagaCompensationDispatcher : ISagaCompensationDispatcher<FulfillmentSaga>
{
    private readonly ISagaCommandDispatcher _dispatcher;
    public FulfillmentSagaCompensationDispatcher(ISagaCommandDispatcher dispatcher) => _dispatcher = dispatcher;

    public async ValueTask CompensateAsync(FulfillmentSaga saga, CancellationToken ct)
    {
        var stateAtFailure = saga.Fsm.Current;
        switch (stateAtFailure)
        {
            default: break;
        }
        saga.Fsm.TryFire(FulfillmentSagaFsm.Trigger.CompensateDone);
    }
}
