//HintName: ExcludedFieldSaga.g.cs
// <auto-generated/>
#nullable enable

namespace Sample;

public partial class ExcludedFieldSaga
{
    public ExcludedFieldSagaFsm Fsm { get; } = new ExcludedFieldSagaFsm();
}
