using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits the AOT-safe per-saga DI registration extension and the matching
/// <see cref="ISagaCompensationDispatcher{TSaga}"/> implementation used by
/// <c>ISagaManager.CompensateAsync</c>.
/// </summary>
internal static class BuilderExtensionsEmitter
{
    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        var sb = new StringBuilder();
        var keyType = TypeNameHelper.GlobalQualified(model.CorrelationKeyTypeFqn);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Saga;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Builder extension class — registers the closed-generic store, lock manager,
        // saga manager, compensation dispatcher, and one INotificationHandler per event.
        sb.Append("public static class ").Append(model.ClassName).AppendLine("BuilderExtensions");
        sb.AppendLine("{");
        sb.Append("    public static ISagaBuilder Add").Append(model.ClassName).AppendLine("(this ISagaBuilder builder)");
        sb.AppendLine("    {");
        // Implicit AddMediator() — idempotent via TryAdd*. Users no longer need
        // to call services.AddMediator() before AddSaga(). The Mediator generator
        // emits AddMediator() into the user's compilation, so this call resolves
        // at the user's build time.
        sb.AppendLine("        builder.Services.AddMediator();");
        // Conditional store registration. v1.1 always registers InMemorySagaStore
        // as the fallback; if a durable backend has been wired (e.g. via
        // WithEfCoreStore<TContext>), the backend installed a SagaStoreRegistrar
        // delegate that overrides the registration. This keeps the generator
        // output free of any direct reference to backend-specific types so
        // users without the Saga.EfCore package compile cleanly.
        sb.Append("        builder.Services.TryAddSingleton<ISagaStore<").Append(model.ClassName).Append(", ").Append(keyType)
          .Append(">, InMemorySagaStore<").Append(model.ClassName).Append(", ").Append(keyType).AppendLine(">>();");
        sb.AppendLine("        if (builder.IsEfCoreBackend)");
        sb.AppendLine("        {");
        sb.Append("            global::ZeroAlloc.Saga.SagaStoreRegistrar.Apply<").Append(model.ClassName).Append(", ").Append(keyType).AppendLine(">(builder);");
        sb.AppendLine("        }");
        sb.Append("        builder.Services.TryAddSingleton<SagaLockManager<").Append(keyType).AppendLine(">>();");
        sb.Append("        builder.Services.TryAddTransient<ISagaCompensationDispatcher<").Append(model.ClassName).Append(">, ").Append(model.ClassName).AppendLine("CompensationDispatcher>();");
        sb.Append("        builder.Services.TryAddTransient<ISagaManager<").Append(model.ClassName).Append(", ").Append(keyType)
          .Append(">, SagaManager<").Append(model.ClassName).Append(", ").Append(keyType).AppendLine(">>();");
        // Default ISagaCommandDispatcher: the per-compilation MediatorSagaCommandDispatcher
        // emitted alongside this file. TryAddScoped so ZeroAlloc.Saga.Outbox.WithOutbox()
        // can Replace it. Scoped to match IMediator's lifetime.
        sb.AppendLine("        builder.Services.TryAddScoped<global::ZeroAlloc.Saga.ISagaCommandDispatcher, global::ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher>();");
        sb.AppendLine();

        var allEvents = model.Steps.Select(s => s.EventTypeFqn)
            .Concat(model.CompensateOnEventFqns)
            .Distinct(System.StringComparer.Ordinal);
        foreach (var evtFqn in allEvents)
        {
            var simple = NameUtil.SimpleName(evtFqn);
            sb.Append("        builder.Services.AddTransient<INotificationHandler<").Append(TypeNameHelper.GlobalQualified(evtFqn)).Append(">, ")
              .Append(model.ClassName).Append("_").Append(simple).AppendLine("_Handler>();");
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Compensation dispatcher — used by ISagaManager.CompensateAsync.
        sb.Append("internal sealed class ").Append(model.ClassName).Append("CompensationDispatcher : ISagaCompensationDispatcher<").Append(model.ClassName).AppendLine(">");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IMediator _mediator;");
        sb.Append("    public ").Append(model.ClassName).AppendLine("CompensationDispatcher(IMediator mediator) => _mediator = mediator;");
        sb.AppendLine();
        sb.Append("    public async ValueTask CompensateAsync(").Append(model.ClassName).AppendLine(" saga, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stateAtFailure = saga.Fsm.Current;");
        sb.AppendLine("        switch (stateAtFailure)");
        sb.AppendLine("        {");
        for (int i = model.Steps.Count - 1; i >= 0; i--)
        {
            var step = model.Steps[i];
            // Only emit a case for steps that have at least one compensation between 1 and i.
            bool hasComp = false;
            for (int k = i; k >= 0; k--)
            {
                if (model.Steps[k].CompensateMethodName is not null) { hasComp = true; break; }
            }
            if (!hasComp) continue;

            sb.Append("            case ").Append(model.ClassName).Append("Fsm.State.Step").Append(i + 1).AppendLine(":");
            for (int j = i; j >= 0; j--)
            {
                var s = model.Steps[j];
                if (s.CompensateMethodName is null) continue;
                sb.Append("                await _mediator.Send(saga.").Append(s.CompensateMethodName).AppendLine("(), ct).ConfigureAwait(false);");
            }
            sb.AppendLine("                break;");
        }
        sb.AppendLine("            default: break;");
        sb.AppendLine("        }");
        sb.Append("        saga.Fsm.TryFire(").Append(model.ClassName).AppendLine("Fsm.Trigger.CompensateDone);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}BuilderExtensions.g.cs", sb.ToString());
    }
}
