using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a static class with one <c>GetKey(TEvent)</c> overload per event
/// type, all routing through a single shared probe instance of the saga
/// (since correlation methods don't read mutable saga state).
/// </summary>
internal static class CorrelationDispatchEmitter
{
    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("internal static class ").Append(model.ClassName).AppendLine("CorrelationDispatch");
        sb.AppendLine("{");
        sb.Append("    private static readonly ").Append(model.ClassName).Append(" _probe = new ").Append(model.ClassName).AppendLine("();");
        sb.AppendLine();

        foreach (var corr in model.Correlations)
        {
            sb.Append("    public static global::").Append(model.CorrelationKeyTypeFqn)
              .Append(" GetKey(global::").Append(corr.EventTypeFqn).Append(" e) => _probe.")
              .Append(corr.MethodName).AppendLine("(e);");
        }

        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}CorrelationDispatch.g.cs", sb.ToString());
    }
}
