using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits the saga's inline FSM partial class. Because Roslyn 4.11 generator
/// chaining does not pick up [StateMachine] companion classes emitted by
/// other generators, this emitter inlines a switch-expression-based TryFire
/// directly — no dependency on ZeroAlloc.StateMachine.Generator.
/// </summary>
internal static class FsmEmitter
{
    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append(model.Accessibility).Append(" partial class ").Append(model.ClassName).AppendLine("Fsm");
        sb.AppendLine("{");

        // ── State enum ──────────────────────────────────────────────────────
        sb.Append("    public enum State { NotStarted");
        for (int i = 1; i <= model.Steps.Count; i++)
            sb.Append(", Step").Append(i);
        sb.AppendLine(", Completed, Compensating, Compensated }");

        // ── Trigger enum ────────────────────────────────────────────────────
        // One trigger per distinct event used + Complete + CompensateDone.
        var triggerNames = new System.Collections.Generic.List<string>();
        var seenTriggers = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal);
        foreach (var step in model.Steps)
        {
            var n = NameUtil.SimpleName(step.EventTypeFqn);
            if (seenTriggers.Add(n)) triggerNames.Add(n);
        }
        foreach (var compFqn in model.CompensateOnEventFqns)
        {
            var n = NameUtil.SimpleName(compFqn);
            if (seenTriggers.Add(n)) triggerNames.Add(n);
        }
        if (seenTriggers.Add("Complete")) triggerNames.Add("Complete");
        if (seenTriggers.Add("CompensateDone")) triggerNames.Add("CompensateDone");

        sb.Append("    public enum Trigger { ").Append(string.Join(", ", triggerNames)).AppendLine(" }");
        sb.AppendLine();

        // ── State field + Current property ──────────────────────────────────
        sb.AppendLine("    private State _state = State.NotStarted;");
        sb.AppendLine("    public State Current => _state;");
        sb.AppendLine();

        // ── TryFire switch expression ───────────────────────────────────────
        sb.AppendLine("    public bool TryFire(Trigger trigger)");
        sb.AppendLine("    {");
        sb.AppendLine("        var next = (_state, trigger) switch");
        sb.AppendLine("        {");

        // Forward transitions: Step i's input event triggers NotStarted/Step(i-1) → Step i.
        for (int i = 0; i < model.Steps.Count; i++)
        {
            var step = model.Steps[i];
            var fromState = i == 0 ? "State.NotStarted" : $"State.Step{i}";
            var toState = $"State.Step{i + 1}";
            var trigger = $"Trigger.{NameUtil.SimpleName(step.EventTypeFqn)}";
            sb.Append("            (").Append(fromState).Append(", ").Append(trigger).Append(") => (State?)").Append(toState).AppendLine(",");
        }

        // Final-step → Completed on Trigger.Complete
        sb.Append("            (State.Step").Append(model.Steps.Count).AppendLine(", Trigger.Complete) => (State?)State.Completed,");

        // Compensation entry: any forward state → Compensating on its CompensateOn trigger.
        for (int i = 0; i < model.Steps.Count; i++)
        {
            var step = model.Steps[i];
            if (step.CompensateOnEventTypeFqn is null) continue;
            var fromState = $"State.Step{i + 1}";
            var trigger = $"Trigger.{NameUtil.SimpleName(step.CompensateOnEventTypeFqn)}";
            sb.Append("            (").Append(fromState).Append(", ").Append(trigger).AppendLine(") => (State?)State.Compensating,");
        }

        // Compensating → Compensated on Trigger.CompensateDone
        sb.AppendLine("            (State.Compensating, Trigger.CompensateDone) => (State?)State.Compensated,");
        sb.AppendLine("            _ => (State?)null");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        if (next is null) return false;");
        sb.AppendLine("        _state = next.Value;");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");

        // Used by ISagaPersistableState.SetFsmStateFromName to rehydrate after
        // load. Kept internal-grade public so generator-emitted partial can
        // call it from another file.
        sb.AppendLine();
        sb.AppendLine("    public void SetCurrentState(State state) => _state = state;");

        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}Fsm.g.cs", sb.ToString());
    }
}
