using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits one <c>INotificationHandler&lt;TEvent&gt;</c> class per event used by
/// the saga (forward-step trigger events plus distinct CompensateOn events).
/// Forward handlers TryFire, dispatch the user's command, and persist; the
/// last step also fires <c>Trigger.Complete</c> and removes the saga.
/// Compensate handlers TryFire to Compensating, walk the reverse cascade,
/// fire <c>Trigger.CompensateDone</c>, and remove the saga.
/// </summary>
/// <remarks>
/// Each emitted handler wraps the load/fire/dispatch/save flow in an OCC
/// retry loop. The catch block matches <c>DbUpdateException</c> AND
/// <c>DbUpdateConcurrencyException</c> by string-name
/// (<c>ex.GetType().FullName == ...</c>) so the generator output never
/// references <c>Microsoft.EntityFrameworkCore</c> — InMemory users compile
/// cleanly without the EF Core package, and the catch is dormant for them
/// because <see cref="ZeroAlloc.Saga.InMemorySagaStore{TSaga,TKey}"/> never
/// throws those exceptions. Both base (<c>DbUpdateException</c>, raised on
/// unique-constraint INSERT races) and derived
/// (<c>DbUpdateConcurrencyException</c>, raised on row-version OCC
/// conflicts) are handled by the same retry path so a fresh-key INSERT
/// race between two processes is recovered just like an UPDATE OCC clash.
/// The retry budget is read from
/// <see cref="ZeroAlloc.Saga.SagaRetryOptions"/>, registered with
/// defaults by <c>AddSaga()</c> and overridden by
/// <c>WithEfCoreStore&lt;TContext&gt;()</c> when EfCore is wired.
/// </remarks>
internal static class HandlerEmitter
{
    private const string DbUpdateConcurrencyExceptionFullName = "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException";
    private const string DbUpdateExceptionFullName = "Microsoft.EntityFrameworkCore.DbUpdateException";

    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        foreach (var step in model.Steps)
        {
            EmitForwardHandler(spc, model, step);
        }

        foreach (var compEventFqn in model.CompensateOnEventFqns)
        {
            EmitCompensateHandler(spc, model, compEventFqn);
        }
    }

    private static void EmitForwardHandler(SourceProductionContext spc, SagaModel model, StepInfo step)
    {
        var sb = new StringBuilder();
        var eventSimple = NameUtil.SimpleName(step.EventTypeFqn);
        var handlerName = $"{model.ClassName}_{eventSimple}_Handler";
        var keyType = TypeNameHelper.GlobalQualified(model.CorrelationKeyTypeFqn);
        var eventType = TypeNameHelper.GlobalQualified(step.EventTypeFqn);
        var fsmType = $"{model.ClassName}Fsm";
        var isLastStep = step.Order == model.Steps[model.Steps.Count - 1].Order;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Saga;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("internal sealed class ").Append(handlerName)
          .Append(" : INotificationHandler<").Append(eventType).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    private readonly ISagaStore<").Append(model.ClassName).Append(", ").Append(keyType).AppendLine("> _store;");
        sb.Append("    private readonly SagaLockManager<").Append(keyType).AppendLine("> _locks;");
        sb.AppendLine("    private readonly IMediator _mediator;");
        sb.AppendLine("    private readonly SagaRetryOptions _retry;");
        sb.Append("    private readonly ILogger<").Append(handlerName).AppendLine("> _log;");
        sb.AppendLine();
        sb.Append("    public ").Append(handlerName).Append("(ISagaStore<").Append(model.ClassName)
          .Append(", ").Append(keyType).Append("> store, SagaLockManager<").Append(keyType)
          .Append("> locks, IMediator mediator, SagaRetryOptions retry, ILogger<").Append(handlerName).AppendLine("> log)");
        sb.AppendLine("    {");
        sb.AppendLine("        _store = store;");
        sb.AppendLine("        _locks = locks;");
        sb.AppendLine("        _mediator = mediator;");
        sb.AppendLine("        _retry = retry;");
        sb.AppendLine("        _log = log;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public async ValueTask Handle(").Append(eventType).AppendLine(" @event, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.Append("        var key = ").Append(model.ClassName).AppendLine("CorrelationDispatch.GetKey(@event);");
        sb.AppendLine("        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        var attempts = 0;");
        sb.AppendLine("        while (true)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var saga = await _store.LoadOrCreateAsync(key, ct).ConfigureAwait(false);");
        sb.Append("                if (!saga.Fsm.TryFire(").Append(fsmType).Append(".Trigger.").Append(eventSimple).AppendLine("))");
        sb.AppendLine("                {");
        sb.Append("                    _log.LogDebug(\"Saga {Saga}: late ").Append(eventSimple).AppendLine(" for key {Key}; ignored\", \"" + model.ClassName + "\", key);");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.Append("                var cmd = saga.").Append(step.MethodName).AppendLine("(@event);");
        sb.AppendLine("                await _mediator.Send(cmd, ct).ConfigureAwait(false);");
        sb.AppendLine();
        if (isLastStep)
        {
            sb.Append("                saga.Fsm.TryFire(").Append(fsmType).AppendLine(".Trigger.Complete);");
            sb.AppendLine("                await _store.RemoveAsync(key, ct).ConfigureAwait(false);");
        }
        else
        {
            sb.AppendLine("                await _store.SaveAsync(key, saga, ct).ConfigureAwait(false);");
        }
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        // String-based type-name catch avoids referencing Microsoft.EntityFrameworkCore
        // from generator output; InMemory users get a dormant catch (their store
        // never raises those exceptions). Both DbUpdateException (e.g. a
        // unique-constraint INSERT race when two processes both create a fresh
        // saga row) and DbUpdateConcurrencyException (UPDATE OCC clash) are
        // recovered by the same retry path.
        sb.AppendLine("            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))");
        sb.AppendLine("            {");
        sb.AppendLine("                attempts++;");
        sb.Append("                _log.LogWarning(\"Saga {Saga}: OCC conflict on key {Key}, retry {Attempt}/{Max}\", \"")
          .Append(model.ClassName).AppendLine("\", key, attempts, _retry.MaxRetryAttempts);");
        sb.AppendLine("                var delay = _retry.UseExponentialBackoff");
        sb.AppendLine("                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))");
        sb.AppendLine("                    : _retry.RetryBaseDelay;");
        sb.AppendLine("                await Task.Delay(delay, ct).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex) when (IsEfCoreConflict(ex))");
        sb.AppendLine("            {");
        sb.Append("                throw new SagaConcurrencyException(\"").Append(model.ClassName).AppendLine("\", key.ToString() ?? string.Empty, attempts, ex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static bool IsEfCoreConflict(Exception ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        var typeName = ex.GetType().FullName;");
        sb.Append("        return typeName == \"").Append(DbUpdateExceptionFullName).AppendLine("\"");
        sb.Append("            || typeName == \"").Append(DbUpdateConcurrencyExceptionFullName).AppendLine("\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{handlerName}.g.cs", sb.ToString());
    }

    private static void EmitCompensateHandler(SourceProductionContext spc, SagaModel model, string compEventFqn)
    {
        var sb = new StringBuilder();
        var eventSimple = NameUtil.SimpleName(compEventFqn);
        var handlerName = $"{model.ClassName}_{eventSimple}_Handler";
        var keyType = TypeNameHelper.GlobalQualified(model.CorrelationKeyTypeFqn);
        var eventType = TypeNameHelper.GlobalQualified(compEventFqn);
        var fsmType = $"{model.ClassName}Fsm";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Saga;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("internal sealed class ").Append(handlerName)
          .Append(" : INotificationHandler<").Append(eventType).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    private readonly ISagaStore<").Append(model.ClassName).Append(", ").Append(keyType).AppendLine("> _store;");
        sb.Append("    private readonly SagaLockManager<").Append(keyType).AppendLine("> _locks;");
        sb.AppendLine("    private readonly IMediator _mediator;");
        sb.AppendLine("    private readonly SagaRetryOptions _retry;");
        sb.Append("    private readonly ILogger<").Append(handlerName).AppendLine("> _log;");
        sb.AppendLine();
        sb.Append("    public ").Append(handlerName).Append("(ISagaStore<").Append(model.ClassName)
          .Append(", ").Append(keyType).Append("> store, SagaLockManager<").Append(keyType)
          .Append("> locks, IMediator mediator, SagaRetryOptions retry, ILogger<").Append(handlerName).AppendLine("> log)");
        sb.AppendLine("    {");
        sb.AppendLine("        _store = store;");
        sb.AppendLine("        _locks = locks;");
        sb.AppendLine("        _mediator = mediator;");
        sb.AppendLine("        _retry = retry;");
        sb.AppendLine("        _log = log;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public async ValueTask Handle(").Append(eventType).AppendLine(" @event, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Resolve the correlation key for this failure event.");
        sb.Append("        var key = ").Append(model.ClassName).AppendLine("CorrelationDispatch.GetKey(@event);");
        sb.AppendLine("        using var _ = await _locks.AcquireAsync(key, ct).ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine("        var attempts = 0;");
        sb.AppendLine("        while (true)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var saga = await _store.TryLoadAsync(key, ct).ConfigureAwait(false);");
        sb.AppendLine("                if (saga is null)");
        sb.AppendLine("                {");
        sb.Append("                    _log.LogWarning(\"Saga {Saga}: orphan ").Append(eventSimple).AppendLine(" for key {Key}; no instance to compensate\", \"" + model.ClassName + "\", key);");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.Append("                var stateAtFailure = saga.Fsm.Current;");
        sb.AppendLine();
        sb.Append("                if (!saga.Fsm.TryFire(").Append(fsmType).Append(".Trigger.").Append(eventSimple).AppendLine("))");
        sb.AppendLine("                {");
        sb.Append("                    _log.LogDebug(\"Saga {Saga}: ").Append(eventSimple).AppendLine(" not valid in state {State} for key {Key}; ignored\", \"" + model.ClassName + "\", stateAtFailure, key);");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                // Reverse-cascade compensation: walk back from stateAtFailure to Step1.");
        sb.AppendLine("                switch (stateAtFailure)");
        sb.AppendLine("                {");
        for (int i = model.Steps.Count - 1; i >= 0; i--)
        {
            var entry = model.Steps[i];
            if (entry.CompensateOnEventTypeFqn != compEventFqn) continue;
            sb.Append("                    case ").Append(fsmType).Append(".State.Step").Append(i + 1).AppendLine(":");
            for (int j = i; j >= 0; j--)
            {
                var s = model.Steps[j];
                if (s.CompensateMethodName is null) continue;
                sb.Append("                        await _mediator.Send(saga.").Append(s.CompensateMethodName).AppendLine("(), ct).ConfigureAwait(false);");
            }
            sb.AppendLine("                        break;");
        }
        sb.AppendLine("                    default: break;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.Append("                saga.Fsm.TryFire(").Append(fsmType).AppendLine(".Trigger.CompensateDone);");
        sb.AppendLine("                await _store.RemoveAsync(key, ct).ConfigureAwait(false);");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        // Note: if RemoveAsync throws DbUpdateConcurrencyException (third-party
        // deleted/updated row mid-compensation), the retry loop re-enters the
        // try block. On retry, TryLoadAsync may return null (just-deleted), and
        // the handler returns silently. However, the compensation commands have
        // already been dispatched once; if the entity is still there on retry,
        // they may be dispatched a second time. The retry-loop's "idempotency
        // is the user's responsibility" contract (ZASAGA015) covers this.
        sb.AppendLine("            catch (Exception ex) when (attempts < _retry.MaxRetryAttempts && IsEfCoreConflict(ex))");
        sb.AppendLine("            {");
        sb.AppendLine("                attempts++;");
        sb.Append("                _log.LogWarning(\"Saga {Saga}: OCC conflict on compensation for key {Key}, retry {Attempt}/{Max}\", \"")
          .Append(model.ClassName).AppendLine("\", key, attempts, _retry.MaxRetryAttempts);");
        sb.AppendLine("                var delay = _retry.UseExponentialBackoff");
        sb.AppendLine("                    ? TimeSpan.FromTicks(_retry.RetryBaseDelay.Ticks * (1L << attempts))");
        sb.AppendLine("                    : _retry.RetryBaseDelay;");
        sb.AppendLine("                await Task.Delay(delay, ct).ConfigureAwait(false);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex) when (IsEfCoreConflict(ex))");
        sb.AppendLine("            {");
        sb.Append("                throw new SagaConcurrencyException(\"").Append(model.ClassName).AppendLine("\", key.ToString() ?? string.Empty, attempts, ex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static bool IsEfCoreConflict(Exception ex)");
        sb.AppendLine("    {");
        sb.AppendLine("        var typeName = ex.GetType().FullName;");
        sb.Append("        return typeName == \"").Append(DbUpdateExceptionFullName).AppendLine("\"");
        sb.Append("            || typeName == \"").Append(DbUpdateConcurrencyExceptionFullName).AppendLine("\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{handlerName}.g.cs", sb.ToString());
    }
}
