#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a single per-compilation
/// <c>ZeroAlloc.Saga.Generated.MediatorSagaCommandDispatcher</c> that switches on
/// the runtime command type and forwards to <see cref="ZeroAlloc.Mediator.IMediator.Send"/>.
/// This is the default <see cref="ZeroAlloc.Saga.ISagaCommandDispatcher"/>
/// implementation; the <c>ZeroAlloc.Saga.Outbox</c> package's <c>WithOutbox()</c>
/// extension replaces it for transactional dispatch.
/// </summary>
/// <remarks>
/// The Saga library cannot reference <c>IMediator</c> directly because that
/// interface is emitted by the Mediator source generator into each consumer
/// assembly. This dispatcher therefore lives in the consumer compilation, where
/// <c>IMediator</c> is in scope.
/// </remarks>
internal static class MediatorSagaCommandDispatcherEmitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<SagaExtractResult> sagaResults, bool registryAlsoEmitted)
    {
        var commandTypes = sagaResults
            .Select(r => r.Model)
            .Where(m => m is not null)
            .SelectMany(m => m!.Steps.SelectMany(st =>
            {
                // Forward step command + (optional) compensation command both need
                // a dispatch arm because saga handlers route compensations through
                // the same ISagaCommandDispatcher abstraction.
                if (st.CompensateCommandTypeFqn is not null)
                    return new[] { st.CommandTypeFqn, st.CompensateCommandTypeFqn };
                return new[] { st.CommandTypeFqn };
            }))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        if (commandTypes.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Saga;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Saga.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Default <see cref=\"ISagaCommandDispatcher\"/> emitted by the Saga generator.");
        sb.AppendLine("/// Forwards to <see cref=\"IMediator.Send\"/> via a switch on the runtime command type.");
        sb.AppendLine("/// Replaced by <c>ZeroAlloc.Saga.Outbox.WithOutbox()</c> for transactional dispatch.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class MediatorSagaCommandDispatcher : ISagaCommandDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IMediator _mediator;");
        if (registryAlsoEmitted)
        {
            // Roots SagaCommandRegistry under PublishAot=true. SagaCommandRegistry
            // is only reachable reflectively from ZeroAlloc.Saga.Outbox's
            // WithOutbox() bootstrapper; without this attribute the trimmer can
            // remove it. MediatorSagaCommandDispatcher is rooted via the
            // generator-emitted Add{Saga}Saga DI registration, so attaching the
            // dependency on its constructor keeps the registry alive whenever
            // a saga consumer also references ZeroAlloc.Serialisation.
            sb.AppendLine("    [DynamicDependency(DynamicallyAccessedMemberTypes.PublicMethods, typeof(SagaCommandRegistry))]");
        }
        sb.AppendLine("    public MediatorSagaCommandDispatcher(IMediator mediator) => _mediator = mediator;");
        sb.AppendLine();
        sb.AppendLine("    public ValueTask DispatchAsync<TCommand>(TCommand cmd, CancellationToken ct)");
        sb.AppendLine("        where TCommand : IRequest<Unit>");
        sb.AppendLine("    {");
        sb.AppendLine("        return cmd switch");
        sb.AppendLine("        {");
        foreach (var fqn in commandTypes)
        {
            var typeExpr = TypeNameHelper.GlobalQualified(fqn);
            sb.Append("            ").Append(typeExpr).Append(" c => Forward(_mediator.Send(c, ct)),").AppendLine();
        }
        sb.AppendLine("            _ => throw new InvalidOperationException(");
        sb.AppendLine("                $\"MediatorSagaCommandDispatcher: no dispatch arm for command type '{typeof(TCommand).FullName}'. The Saga generator did not emit a Send call for this type — ensure the type is referenced from a [Step] method's return type in this compilation.\")");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        static ValueTask Forward(ValueTask<Unit> task)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (task.IsCompletedSuccessfully) { _ = task.Result; return ValueTask.CompletedTask; }");
        sb.AppendLine("            return ConvertAsync(task);");
        sb.AppendLine();
        sb.AppendLine("            static async ValueTask ConvertAsync(ValueTask<Unit> t) => await t.ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("MediatorSagaCommandDispatcher.g.cs", sb.ToString());
    }
}
