using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a partial declaration of the user's saga class that attaches the
/// generated <c>Fsm</c> companion as an instance property.
/// </summary>
internal static class PartialCompletionEmitter
{
    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append(model.Accessibility).Append(" partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");
        sb.Append("    public ").Append(model.ClassName).Append("Fsm Fsm { get; } = new ").Append(model.ClassName).AppendLine("Fsm();");
        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}.g.cs", sb.ToString());
    }
}
