#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a single per-compilation <c>ZeroAlloc.Saga.Generated.SagaCommandRegistry</c>. It lists
/// every distinct command type used by sagas in the compilation, forward step commands AND
/// compensation commands, and maps each one's type name to a typed deserialize-and-dispatch path.
///
/// <c>ZeroAlloc.Saga.Outbox</c>'s <c>WithOutbox()</c> finds it by reflection: <c>GetTypeNames()</c>
/// tells it which outbox dispatchers to register, and each of them calls <c>DispatchAsync</c>.
/// Emission is conditional on the consumer referencing <c>ZeroAlloc.Serialisation</c>
/// (detected via <c>Compilation.GetTypeByMetadataName("ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute")</c>);
/// see <see cref="SagaGenerator"/>.
/// </summary>
internal static class SagaCommandRegistryEmitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<SagaExtractResult> sagaResults)
    {
        var commandTypes = sagaResults
            .Select(r => r.Model)
            .Where(m => m is not null)
            .SelectMany(m => m!.Steps.SelectMany(st =>
            {
                // Forward step command + (optional) compensation command both need
                // an entry: the outbox bridge dispatches both through this registry —
                // same union as the MediatorSagaCommandDispatcher.
                if (st.CompensateCommandTypeFqn is not null)
                    return new[] { st.CommandTypeFqn, st.CompensateCommandTypeFqn };
                return new[] { st.CommandTypeFqn };
            }))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        if (commandTypes.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Serialisation;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Saga.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Per-compilation table that maps an outbox entry's <c>typeName</c> to a typed");
        sb.AppendLine("/// deserialize-via-<see cref=\"ISerializer{T}\"/> and dispatch-via-<see cref=\"IMediator.Send\"/> path.");
        sb.AppendLine("/// <c>ZeroAlloc.Saga.Outbox</c>'s <c>WithOutbox()</c> reaches it reflectively and registers one");
        sb.AppendLine("/// outbox dispatcher per name <see cref=\"GetTypeNames\"/> returns.");
        sb.AppendLine("/// </summary>");
        // internal, not public: DispatchAsync takes IMediator, which ZeroAlloc.Mediator's
        // generator emits as an internal interface per consumer compilation from v5 onward.
        // A public method cannot expose an internal parameter type — CS0051. Nothing outside
        // this compilation references the registry by name anyway; ZeroAlloc.Saga.Outbox
        // finds it by reflection, and its delegate is deliberately IMediator-free precisely
        // because the type does not exist outside the consumer's assembly.
        sb.AppendLine("internal static class SagaCommandRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    // Type.FullName of every saga step and compensation command. OutboxSagaCommandDispatcher");
        sb.AppendLine("    // writes the same expression as the outbox entry's type name, so nested and generic");
        sb.AppendLine("    // command types match as well.");
        sb.AppendLine("    private static readonly string[] s_typeNames =");
        sb.AppendLine("    {");
        foreach (var fqn in commandTypes)
        {
            // Model FQNs are already global-prefix-stripped (SagaModel.StripGlobalPrefix);
            // GlobalQualified adds "global::" back to avoid namespace ambiguity.
            sb.Append("        typeof(").Append(TypeNameHelper.GlobalQualified(fqn)).AppendLine(").FullName!,");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Every <c>typeName</c> that <see cref=\"DispatchAsync\"/> accepts.</summary>");
        sb.AppendLine("    internal static IReadOnlyList<string> GetTypeNames() => s_typeNames;");
        sb.AppendLine();
        sb.AppendLine("    internal static async ValueTask DispatchAsync(");
        sb.AppendLine("        string typeName,");
        sb.AppendLine("        ReadOnlyMemory<byte> bytes,");
        sb.AppendLine("        IServiceProvider services,");
        sb.AppendLine("        IMediator mediator,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        for (var i = 0; i < commandTypes.Count; i++)
        {
            var fqn = commandTypes[i];
            var typeExpr = TypeNameHelper.GlobalQualified(fqn);
            sb.Append("        if (string.Equals(typeName, s_typeNames[")
              .Append(i.ToString(System.Globalization.CultureInfo.InvariantCulture))
              .AppendLine("], StringComparison.Ordinal))");
            sb.AppendLine("        {");
            sb.Append("            var serializer = services.GetRequiredService<ISerializer<").Append(typeExpr).AppendLine(">>();");
            sb.AppendLine("            var cmd = serializer.Deserialize(bytes.Span);");
            sb.AppendLine("            if (cmd is null)");
            sb.Append("                throw new InvalidOperationException(\"ISerializer.Deserialize returned null for ").Append(fqn).AppendLine(".\");");
            sb.AppendLine("            await mediator.Send(cmd, ct).ConfigureAwait(false);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("        throw new InvalidOperationException(");
        sb.AppendLine("            $\"Unknown saga command type '{typeName}'. The outbox entry references a type that the Saga generator did not emit a dispatcher for.\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("SagaCommandRegistry.g.cs", sb.ToString());
    }
}
