#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a single per-compilation public static class
/// <c>ZeroAlloc.Saga.Generated.SagaCommandRegistry</c> with a typed-deserialize-and-dispatch
/// switch over every distinct command type used by sagas in the compilation
/// (forward step commands AND compensation commands).
///
/// Used by <c>ZeroAlloc.Saga.Outbox</c>'s poller to dispatch enqueued saga commands.
/// Emission is conditional on the consumer referencing <c>ZeroAlloc.Serialisation</c>
/// (detected via <c>Compilation.GetTypeByMetadataName("ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute")</c>);
/// see <see cref="SagaGenerator"/>.
/// </summary>
internal static class SagaCommandRegistryEmitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<SagaExtractResult> sagaResults)
    {
        var commandTypes = sagaResults
            .Select(r => r.Model)
            .Where(m => m is not null)
            .SelectMany(m => m!.Steps.SelectMany(st =>
            {
                // Forward step command + (optional) compensation command both need
                // an arm: the outbox poller uses this registry for both forward
                // and compensation dispatch — same union as the
                // MediatorSagaCommandDispatcher.
                if (st.CompensateCommandTypeFqn is not null)
                    return new[] { st.CommandTypeFqn, st.CompensateCommandTypeFqn };
                return new[] { st.CommandTypeFqn };
            }))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        if (commandTypes.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Serialisation;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Saga.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Per-compilation switch table that maps an outbox entry's <c>typeName</c> to a typed");
        sb.AppendLine("/// deserialize-via-<see cref=\"ISerializer{T}\"/> and dispatch-via-<see cref=\"IMediator.Send\"/> path.");
        sb.AppendLine("/// Consumed by <c>ZeroAlloc.Saga.Outbox.OutboxSagaCommandPoller</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SagaCommandRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static async ValueTask DispatchAsync(");
        sb.AppendLine("        string typeName,");
        sb.AppendLine("        ReadOnlyMemory<byte> bytes,");
        sb.AppendLine("        IServiceProvider services,");
        sb.AppendLine("        IMediator mediator,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (typeName)");
        sb.AppendLine("        {");
        foreach (var fqn in commandTypes)
        {
            // Model FQNs are already global-prefix-stripped (SagaModel.StripGlobalPrefix),
            // so `fqn` is the bare type name e.g. "Sample.ReserveCmd". Use it directly
            // as the case label (matching the typeName written by the outbox bridge).
            // For C# type expressions we add the "global::" prefix to avoid namespace
            // ambiguity in the consumer compilation.
            var typeExpr = TypeNameHelper.GlobalQualified(fqn);
            sb.Append("            case \"").Append(fqn).AppendLine("\":");
            sb.AppendLine("            {");
            sb.Append("                var serializer = services.GetRequiredService<ISerializer<").Append(typeExpr).AppendLine(">>();");
            sb.AppendLine("                var cmd = serializer.Deserialize(bytes.Span);");
            sb.AppendLine("                if (cmd is null)");
            sb.Append("                    throw new InvalidOperationException(\"ISerializer.Deserialize returned null for ").Append(fqn).AppendLine(".\");");
            sb.AppendLine("                await mediator.Send(cmd, ct).ConfigureAwait(false);");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
        }
        sb.AppendLine("            default:");
        sb.AppendLine("                throw new InvalidOperationException(");
        sb.AppendLine("                    $\"Unknown saga command type '{typeName}'. The outbox entry references a type that the Saga generator did not emit a dispatcher for.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("SagaCommandRegistry.g.cs", sb.ToString());
    }
}
