#nullable enable
using ZeroAlloc.Saga.Generator.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a single per-compilation <c>ZeroAlloc.Saga.Generated.SagaCommandRegistry</c>. It lists
/// every distinct command type used by sagas in the compilation, forward step commands AND
/// compensation commands, and maps each one's type name to a typed deserialize-and-dispatch path.
///
/// The generated <c>GeneratedSagaCommandSource</c> calls <c>DispatchAsync</c> from its
/// <c>DispatchSerializedAsync</c>, which <c>ZeroAlloc.Saga.Outbox</c>'s outbox dispatchers call.
/// Emission is conditional on the consumer referencing <c>ZeroAlloc.Serialisation</c>
/// (detected via <c>Compilation.GetTypeByMetadataName("ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute")</c>);
/// see <see cref="SagaGenerator"/>.
/// </summary>
internal static class SagaCommandRegistryEmitter
{
    public static void Emit(SourceProductionContext spc, EquatableArray<SagaExtractResult> sagaResults)
    {
        var commandTypes = SagaCommandTypes.Collect(sagaResults);

        if (commandTypes.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Serialisation;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Saga.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Per-compilation table that maps an outbox entry's <c>typeName</c> to a typed");
        sb.AppendLine("/// deserialize-via-<see cref=\"ISerializer{T}\"/> and dispatch-via-<see cref=\"IMediator.Send\"/> path.");
        sb.AppendLine("/// <see cref=\"GeneratedSagaCommandSource\"/> calls it for every saga command that");
        sb.AppendLine("/// <c>ZeroAlloc.Saga.Outbox</c>'s outbox dispatchers read from the outbox.");
        sb.AppendLine("/// </summary>");
        // internal, not public: DispatchAsync takes IMediator, which ZeroAlloc.Mediator's
        // generator emits as an internal interface per consumer compilation from v5 onward.
        // A public method cannot expose an internal parameter type — CS0051. Nothing outside
        // this compilation references the registry: GeneratedSagaCommandSource, in the same
        // compilation, calls it, and SagaCommandSource is deliberately IMediator-free precisely
        // because the type does not exist outside the consumer's assembly.
        sb.AppendLine("internal static class SagaCommandRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    // Type.FullName of every saga step and compensation command. OutboxSagaCommandDispatcher");
        sb.AppendLine("    // writes the same expression as the outbox entry's type name, so nested and generic");
        sb.AppendLine("    // command types match as well.");
        sb.AppendLine("    private static readonly string[] s_typeNames =");
        sb.AppendLine("    {");
        foreach (var commandType in commandTypes)
        {
            // Model FQNs are already global-prefix-stripped (SagaModel.StripGlobalPrefix);
            // GlobalQualified adds "global::" back to avoid namespace ambiguity.
            sb.Append("        typeof(").Append(TypeNameHelper.GlobalQualified(commandType.Fqn)).AppendLine(").FullName!,");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    internal static async ValueTask DispatchAsync(");
        sb.AppendLine("        string typeName,");
        sb.AppendLine("        ReadOnlyMemory<byte> bytes,");
        sb.AppendLine("        IServiceProvider services,");
        sb.AppendLine("        IMediator mediator,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        for (var i = 0; i < commandTypes.Count; i++)
        {
            var commandType = commandTypes[i];
            var typeExpr = TypeNameHelper.GlobalQualified(commandType.Fqn);
            sb.Append("        if (string.Equals(typeName, s_typeNames[")
              .Append(i.ToString(System.Globalization.CultureInfo.InvariantCulture))
              .AppendLine("], StringComparison.Ordinal))");
            sb.AppendLine("        {");
            sb.Append("            var serializer = services.GetRequiredService<ISerializer<").Append(typeExpr).AppendLine(">>();");
            sb.AppendLine("            var cmd = serializer.Deserialize(bytes.Span);");
            // ISerializer<T>.Deserialize returns an unconstrained T?, which is plain T for a
            // struct: a struct command is never null, and comparing it to null is CS0037.
            if (commandType.IsReferenceType)
            {
                sb.AppendLine("            if (cmd is null)");
                sb.Append("                throw new InvalidOperationException(\"ISerializer.Deserialize returned null for ").Append(commandType.Fqn).AppendLine(".\");");
            }
            sb.AppendLine("            await mediator.Send(cmd, ct).ConfigureAwait(false);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("        throw new InvalidOperationException(");
        sb.AppendLine("            $\"Unknown saga command type '{typeName}'. The outbox entry references a type that the Saga generator did not emit a dispatcher for.\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("SagaCommandRegistry.g.cs", sb.ToString());
    }
}
