#nullable enable
using ZeroAlloc.Saga.Generator.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits a single per-compilation <c>ZeroAlloc.Saga.Generated.GeneratedSagaCommandSource</c>: the
/// <c>ZeroAlloc.Saga.SagaCommandSource</c> that lists this assembly's saga command types and
/// dispatches them through this assembly's <c>IMediator</c>. Every <c>With{Saga}()</c> adds it to
/// the builder, so an application with sagas in several assemblies registers one source per
/// assembly, and the runtime dispatches each command through the assembly that declares it. See #176.
/// </summary>
/// <remarks>
/// It references <c>MediatorSagaCommandDispatcher</c> and, when emitted, <c>SagaCommandRegistry</c>
/// directly, so nothing is found by reflection and the trimmer keeps both under PublishAot.
/// </remarks>
internal static class SagaCommandSourceEmitter
{
    public static void Emit(SourceProductionContext spc, EquatableArray<SagaExtractResult> sagaResults, bool registryAlsoEmitted)
    {
        var commandTypes = SagaCommandTypes.Collect(sagaResults);
        if (commandTypes.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine("using ZeroAlloc.Saga;");
        sb.AppendLine();
        sb.AppendLine("namespace ZeroAlloc.Saga.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// This assembly's saga commands. Every generator-emitted <c>With{Saga}()</c> in this assembly");
        sb.AppendLine("/// adds it to the saga builder, so commands are dispatched through this assembly's");
        sb.AppendLine("/// <see cref=\"IMediator\"/> even when other assemblies declare sagas too.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class GeneratedSagaCommandSource : SagaCommandSource");
        sb.AppendLine("{");
        sb.AppendLine("    internal static readonly GeneratedSagaCommandSource Instance = new();");
        sb.AppendLine();
        sb.AppendLine("    private static readonly Type[] s_commandTypes =");
        sb.AppendLine("    {");
        foreach (var commandType in commandTypes)
        {
            sb.Append("        typeof(").Append(TypeNameHelper.GlobalQualified(commandType.Fqn)).AppendLine("),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    private GeneratedSagaCommandSource()");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override IReadOnlyList<Type> CommandTypes => s_commandTypes;");
        sb.AppendLine();
        sb.AppendLine("    public override ISagaCommandDispatcher CreateDispatcher(IServiceProvider services)");
        sb.AppendLine("        => new MediatorSagaCommandDispatcher(services.GetRequiredService<IMediator>());");
        if (registryAlsoEmitted)
        {
            sb.AppendLine();
            sb.AppendLine("    public override bool CanDispatchSerialized => true;");
            sb.AppendLine();
            sb.AppendLine("    public override ValueTask DispatchSerializedAsync(");
            sb.AppendLine("        string typeName,");
            sb.AppendLine("        ReadOnlyMemory<byte> payload,");
            sb.AppendLine("        IServiceProvider services,");
            sb.AppendLine("        CancellationToken ct)");
            sb.AppendLine("        => SagaCommandRegistry.DispatchAsync(typeName, payload, services, services.GetRequiredService<IMediator>(), ct);");
            sb.AppendLine();
            // One closed-generic lookup per command type, so the check needs no MakeGenericType
            // and stays AOT-safe.
            sb.AppendLine("    public override IReadOnlyList<Type> GetCommandTypesWithoutSerializer(IServiceProvider services)");
            sb.AppendLine("    {");
            sb.AppendLine("        List<Type>? missing = null;");
            foreach (var commandType in commandTypes)
            {
                var typeExpr = TypeNameHelper.GlobalQualified(commandType.Fqn);
                sb.Append("        if (services.GetService<global::ZeroAlloc.Serialisation.ISerializer<").Append(typeExpr).AppendLine(">>() is null)");
                sb.Append("            (missing ??= new List<Type>()).Add(typeof(").Append(typeExpr).AppendLine("));");
            }
            sb.AppendLine("        return (IReadOnlyList<Type>?)missing ?? Array.Empty<Type>();");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");

        spc.AddSource("GeneratedSagaCommandSource.g.cs", sb.ToString());
    }
}
