#nullable enable
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// When <c>ZeroAlloc.Serialisation</c> is referenced, auto-applies
/// <c>[ZeroAllocSerializable(SerializationFormat.Json)]</c> to each step command type via a
/// partial-class extension. C# attribute merging across partial declarations means
/// <c>ZeroAlloc.Serialisation.Generator</c> (running in the same compilation) picks up
/// the attribute and emits its <c>ISerializer&lt;T&gt;</c>. User-applied
/// <c>[ZeroAllocSerializable]</c> always wins (the emitter detects the existing
/// attribute and skips its own emission so the user's chosen format is preserved).
///
/// Skip conditions:
///   - <c>ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute</c> not found in references.
///   - Step command type is in a referenced assembly (cross-assembly — covered by ZASAGA017).
///   - Step command type is not declared <c>partial</c> (covered by ZASAGA016).
///   - User already applied <c>[ZeroAllocSerializable]</c> on their own declaration.
/// </summary>
internal static class SerializableExtensionEmitter
{
    public static void Emit(
        SourceProductionContext spc,
        ImmutableArray<SagaExtractResult> sagaResults,
        Compilation compilation)
    {
        var serialisableAttr = compilation.GetTypeByMetadataName(
            "ZeroAlloc.Serialisation.ZeroAllocSerializableAttribute");
        if (serialisableAttr is null) return;

        // De-dupe by command type FQN so a single command used by multiple steps
        // / sagas only produces a single generated partial.
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var result in sagaResults)
        {
            var model = result.Model;
            if (model is null) continue;
            foreach (var step in model.Steps)
            {
                EmitFor(
                    spc,
                    step.CommandTypeFqn,
                    step.CommandTypeIsInOwnAssembly,
                    step.CommandTypeIsPartial,
                    compilation,
                    serialisableAttr,
                    seen);
            }
        }
    }

    private static void EmitFor(
        SourceProductionContext spc,
        string commandFqn,
        bool? isInOwnAssembly,
        bool isPartial,
        Compilation compilation,
        INamedTypeSymbol serialisableAttr,
        HashSet<string> seen)
    {
        if (!seen.Add(commandFqn)) return;
        if (isInOwnAssembly != true) return;  // ZASAGA017 covers cross-assembly
        if (!isPartial) return;               // ZASAGA016 covers non-partial

        var symbol = compilation.GetTypeByMetadataName(commandFqn);
        if (symbol is null) return;

        // User-applied attribute wins — skip emission entirely so their
        // chosen format isn't overridden.
        if (symbol.GetAttributes().Any(a =>
                SymbolEqualityComparer.Default.Equals(a.AttributeClass, serialisableAttr)))
        {
            return;
        }

        // Determine the type-keyword sequence based on the symbol's shape.
        // C# attribute merging requires the same type-keyword sequence on every
        // partial declaration ("partial record struct" / "partial record" /
        // "partial struct" / "partial class"). The compiler resolves "partial
        // record" against the original positional-record declaration.
        var typeKindKeyword = (symbol.IsRecord, symbol.IsValueType) switch
        {
            (true, true) => "record struct",
            (true, false) => "record",
            (false, true) => "struct",
            (false, false) => "class",
        };

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        // Hint name uses the FQN with '.' replaced so types in different
        // namespaces with the same simple name don't collide.
        var safeName = commandFqn.Replace('.', '_');

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using ZeroAlloc.Serialisation;");
        sb.AppendLine();
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.AppendLine("[ZeroAllocSerializable(SerializationFormat.Json)]");
        sb.Append("partial ").Append(typeKindKeyword).Append(' ').Append(symbol.Name).AppendLine(";");

        spc.AddSource($"{safeName}.SagaSerializable.g.cs", sb.ToString());
    }
}
