using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Saga.Generator;

/// <summary>
/// Emits the saga's <see cref="ISagaPersistableState"/> implementation as a
/// partial-class completion: <c>Snapshot()</c>, <c>Restore(ReadOnlySpan&lt;byte&gt;)</c>,
/// <c>CurrentFsmStateName</c>, and <c>SetFsmStateFromName(string)</c>.
/// </summary>
/// <remarks>
/// The emitted Snapshot() prefixes the body with a single version byte (constant
/// <c>SagaStateVersion = 1</c>) and writes each state field via the typed
/// <c>SagaStateWriter</c> primitives. Restore validates the version and throws
/// <c>SagaStateVersionMismatchException</c> on mismatch. Skipped entirely if any
/// state field has Kind == Unsupported (ZASAGA014 already reported).
/// </remarks>
internal static class SnapshotRestoreEmitter
{
    public static void Emit(SourceProductionContext spc, SagaModel model)
    {
        // Skip if any unsupported field — generator already reported ZASAGA014.
        if (model.StateFields.Any(f => f.Kind == StateFieldKind.Unsupported))
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append(model.Accessibility).Append(" partial class ").Append(model.ClassName)
          .AppendLine(" : global::ZeroAlloc.Saga.ISagaPersistableState");
        sb.AppendLine("{");
        sb.AppendLine("    private const byte SagaStateVersion = 1;");
        sb.AppendLine();

        // Snapshot()
        sb.AppendLine("    public byte[] Snapshot()");
        sb.AppendLine("    {");
        sb.AppendLine("        var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>(initialCapacity: 64);");
        sb.AppendLine("        var __w = new global::ZeroAlloc.Saga.SagaStateWriter(__buffer);");
        sb.AppendLine("        __w.WriteByte(SagaStateVersion);");
        foreach (var field in model.StateFields)
        {
            sb.Append("        ").AppendLine(EmitWrite(field, "__w", $"this.{field.MemberName}"));
        }
        sb.AppendLine("        return __buffer.WrittenSpan.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Restore(ReadOnlySpan<byte>)
        sb.AppendLine("    public void Restore(global::System.ReadOnlySpan<byte> data)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __r = new global::ZeroAlloc.Saga.SagaStateReader(data);");
        sb.AppendLine("        var __version = __r.ReadByte();");
        sb.AppendLine("        if (__version != SagaStateVersion)");
        sb.Append("            throw new global::ZeroAlloc.Saga.SagaStateVersionMismatchException(\"")
          .Append(string.IsNullOrEmpty(model.Namespace) ? model.ClassName : model.Namespace + "." + model.ClassName)
          .AppendLine("\", SagaStateVersion, __version);");
        foreach (var field in model.StateFields)
        {
            sb.Append("        ").AppendLine(EmitRead(field, "__r", $"this.{field.MemberName}"));
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // CurrentFsmStateName
        sb.AppendLine("    public string CurrentFsmStateName => Fsm.Current.ToString();");
        sb.AppendLine();

        // SetFsmStateFromName(string)
        sb.AppendLine("    public void SetFsmStateFromName(string stateName)");
        sb.AppendLine("    {");
        sb.Append("        var parsed = global::System.Enum.Parse<").Append(model.ClassName).AppendLine("Fsm.State>(stateName);");
        sb.AppendLine("        Fsm.SetCurrentState(parsed);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}.PersistableState.g.cs", sb.ToString());
    }

    private static string EmitWrite(StateFieldInfo field, string writer, string accessor) =>
        field.Kind switch
        {
            StateFieldKind.Byte => $"{writer}.WriteByte({accessor});",
            StateFieldKind.SByte => $"{writer}.WriteSByte({accessor});",
            StateFieldKind.Int16 => $"{writer}.WriteInt16({accessor});",
            StateFieldKind.UInt16 => $"{writer}.WriteUInt16({accessor});",
            StateFieldKind.Int32 => $"{writer}.WriteInt32({accessor});",
            StateFieldKind.UInt32 => $"{writer}.WriteUInt32({accessor});",
            StateFieldKind.Int64 => $"{writer}.WriteInt64({accessor});",
            StateFieldKind.UInt64 => $"{writer}.WriteUInt64({accessor});",
            StateFieldKind.Single => $"{writer}.WriteSingle({accessor});",
            StateFieldKind.Double => $"{writer}.WriteDouble({accessor});",
            StateFieldKind.Decimal => $"{writer}.WriteDecimal({accessor});",
            StateFieldKind.Boolean => $"{writer}.WriteBoolean({accessor});",
            StateFieldKind.String => $"{writer}.WriteString({accessor});",
            StateFieldKind.DateTime => $"{writer}.WriteDateTime({accessor});",
            StateFieldKind.DateTimeOffset => $"{writer}.WriteDateTimeOffset({accessor});",
            StateFieldKind.TimeSpan => $"{writer}.WriteTimeSpan({accessor});",
            StateFieldKind.Guid => $"{writer}.WriteGuid({accessor});",
            StateFieldKind.ByteArray => $"{writer}.WriteBytes({accessor});",
            StateFieldKind.Enum => EmitEnumWrite(field, writer, accessor),
            StateFieldKind.TypedId => EmitTypedIdWrite(field, writer, accessor),
            StateFieldKind.Nullable => EmitNullableWrite(field, writer, accessor),
            _ => $"// Unsupported kind {field.Kind} for {field.MemberName}",
        };

    private static string EmitEnumWrite(StateFieldInfo field, string writer, string accessor)
    {
        var k = field.EnumUnderlyingKind ?? StateFieldKind.Int32;
        var prim = WriteSuffix(k);
        var underlyingType = PrimitiveCSharpName(k);
        return $"{writer}.Write{prim}(({underlyingType}){accessor});";
    }

    private static string EmitTypedIdWrite(StateFieldInfo field, string writer, string accessor)
    {
        var k = field.TypedIdValuePrimitiveKind ?? StateFieldKind.Guid;
        var prim = WriteSuffix(k);
        // For [TypedId] structs we use .Value; for positional `record struct Foo(int Bar)`
        // shapes we read back via the parameter name (Bar).
        var member = field.RecordPositionalParamName ?? "Value";
        return $"{writer}.Write{prim}({accessor}.{member});";
    }

    private static string EmitNullableWrite(StateFieldInfo field, string writer, string accessor)
    {
        // Layout: 1 byte flag (1 = present, 0 = null), then inner-Write-call when present.
        var inner = field.InnerKind ?? StateFieldKind.Int32;
        // Synthesize a child field for the inner emit. Pass via a fake StateFieldInfo
        // so EmitWrite can recurse on the inner kind cleanly.
        var innerField = field with { Kind = inner, InnerKind = null };
        // For the inner emit we need to write the underlying value (.Value on the nullable).
        var innerAccessor = $"{accessor}.Value";
        var innerWrite = EmitWrite(innerField, writer, innerAccessor);
        return $"if ({accessor}.HasValue) {{ {writer}.WriteBoolean(true); {innerWrite} }} else {{ {writer}.WriteBoolean(false); }}";
    }

    private static string EmitRead(StateFieldInfo field, string reader, string accessor) =>
        field.Kind switch
        {
            StateFieldKind.Byte => $"{accessor} = {reader}.ReadByte();",
            StateFieldKind.SByte => $"{accessor} = {reader}.ReadSByte();",
            StateFieldKind.Int16 => $"{accessor} = {reader}.ReadInt16();",
            StateFieldKind.UInt16 => $"{accessor} = {reader}.ReadUInt16();",
            StateFieldKind.Int32 => $"{accessor} = {reader}.ReadInt32();",
            StateFieldKind.UInt32 => $"{accessor} = {reader}.ReadUInt32();",
            StateFieldKind.Int64 => $"{accessor} = {reader}.ReadInt64();",
            StateFieldKind.UInt64 => $"{accessor} = {reader}.ReadUInt64();",
            StateFieldKind.Single => $"{accessor} = {reader}.ReadSingle();",
            StateFieldKind.Double => $"{accessor} = {reader}.ReadDouble();",
            StateFieldKind.Decimal => $"{accessor} = {reader}.ReadDecimal();",
            StateFieldKind.Boolean => $"{accessor} = {reader}.ReadBoolean();",
            StateFieldKind.String => $"{accessor} = {reader}.ReadString()!;",
            StateFieldKind.DateTime => $"{accessor} = {reader}.ReadDateTime();",
            StateFieldKind.DateTimeOffset => $"{accessor} = {reader}.ReadDateTimeOffset();",
            StateFieldKind.TimeSpan => $"{accessor} = {reader}.ReadTimeSpan();",
            StateFieldKind.Guid => $"{accessor} = {reader}.ReadGuid();",
            StateFieldKind.ByteArray => $"{accessor} = {reader}.ReadBytes()!;",
            StateFieldKind.Enum => EmitEnumRead(field, reader, accessor),
            StateFieldKind.TypedId => EmitTypedIdRead(field, reader, accessor),
            StateFieldKind.Nullable => EmitNullableRead(field, reader, accessor),
            _ => $"// Unsupported kind {field.Kind} for {field.MemberName}",
        };

    private static string EmitEnumRead(StateFieldInfo field, string reader, string accessor)
    {
        var k = field.EnumUnderlyingKind ?? StateFieldKind.Int32;
        var prim = ReadSuffix(k);
        return $"{accessor} = (global::{field.TypeFqn}){reader}.Read{prim}();";
    }

    private static string EmitTypedIdRead(StateFieldInfo field, string reader, string accessor)
    {
        var k = field.TypedIdValuePrimitiveKind ?? StateFieldKind.Guid;
        var prim = ReadSuffix(k);
        return $"{accessor} = new global::{field.TypeFqn}({reader}.Read{prim}());";
    }

    private static string EmitNullableRead(StateFieldInfo field, string reader, string accessor)
    {
        var inner = field.InnerKind ?? StateFieldKind.Int32;
        // Inner field info to recurse with its kind. The accessor for an inner
        // primitive read is an explicit conversion target; for the nullable
        // wrapper we wrap with a temp.
        var innerField = field with { Kind = inner, InnerKind = null };
        var tmp = $"__nv_{field.MemberName}";
        // Build via local then assign. Use a compound { } block.
        // For struct primitives accessor is e.g. this.X = (T)tmp; we can use the same
        // EmitRead but pointing at a local var declaration to extract the inner value,
        // then assign accessor = tmp.
        var innerRead = EmitRead(innerField, reader, tmp);
        // Inner read includes the assignment "tmp = reader.ReadX();" — strip the leading
        // "var "? It's just an assignment target; we can pre-declare tmp.
        return $"if ({reader}.ReadBoolean()) {{ {InnerCSharpType(innerField)} {tmp}; {innerRead} {accessor} = {tmp}; }} else {{ {accessor} = null; }}";
    }

    private static string InnerCSharpType(StateFieldInfo field) =>
        field.Kind switch
        {
            StateFieldKind.Byte => "byte",
            StateFieldKind.SByte => "sbyte",
            StateFieldKind.Int16 => "short",
            StateFieldKind.UInt16 => "ushort",
            StateFieldKind.Int32 => "int",
            StateFieldKind.UInt32 => "uint",
            StateFieldKind.Int64 => "long",
            StateFieldKind.UInt64 => "ulong",
            StateFieldKind.Single => "float",
            StateFieldKind.Double => "double",
            StateFieldKind.Decimal => "decimal",
            StateFieldKind.Boolean => "bool",
            StateFieldKind.String => "string",
            StateFieldKind.DateTime => "global::System.DateTime",
            StateFieldKind.DateTimeOffset => "global::System.DateTimeOffset",
            StateFieldKind.TimeSpan => "global::System.TimeSpan",
            StateFieldKind.Guid => "global::System.Guid",
            StateFieldKind.ByteArray => "byte[]",
            StateFieldKind.Enum or StateFieldKind.TypedId => "global::" + field.TypeFqn,
            _ => "object",
        };

    private static string WriteSuffix(StateFieldKind k) => k switch
    {
        StateFieldKind.Byte => "Byte",
        StateFieldKind.SByte => "SByte",
        StateFieldKind.Int16 => "Int16",
        StateFieldKind.UInt16 => "UInt16",
        StateFieldKind.Int32 => "Int32",
        StateFieldKind.UInt32 => "UInt32",
        StateFieldKind.Int64 => "Int64",
        StateFieldKind.UInt64 => "UInt64",
        StateFieldKind.Single => "Single",
        StateFieldKind.Double => "Double",
        StateFieldKind.Decimal => "Decimal",
        StateFieldKind.Boolean => "Boolean",
        StateFieldKind.String => "String",
        StateFieldKind.DateTime => "DateTime",
        StateFieldKind.DateTimeOffset => "DateTimeOffset",
        StateFieldKind.TimeSpan => "TimeSpan",
        StateFieldKind.Guid => "Guid",
        StateFieldKind.ByteArray => "Bytes",
        _ => "Int32",
    };

    private static string ReadSuffix(StateFieldKind k) => WriteSuffix(k);

    private static string PrimitiveCSharpName(StateFieldKind k) => k switch
    {
        StateFieldKind.Byte => "byte",
        StateFieldKind.SByte => "sbyte",
        StateFieldKind.Int16 => "short",
        StateFieldKind.UInt16 => "ushort",
        StateFieldKind.Int32 => "int",
        StateFieldKind.UInt32 => "uint",
        StateFieldKind.Int64 => "long",
        StateFieldKind.UInt64 => "ulong",
        _ => "int",
    };
}
